#include "layouts-generated.h"
#define LAYERS 8
static const Key keymaps[LAYERS][ROWS][COLS] = {
	KEYMAP_QWERTY
	KEYMAP_QWERTY_FN2
    KEYMAP_COLEMAK
    KEYMAP_COLEMAK_FN2
    KEYMAP_DVORAK
    KEYMAP_DVORAK_FN2
    KEYMAP_WORKMAN
    KEYMAP_WORKMAN_FN2




};

