// -*- c++ -*-

#pragma once

#include <kaleidoscope/key_defs.h>
#include <kaleidoscope/KeyAddr.h>

namespace kaleidoscope {
namespace testing {

constexpr KeyAddr addr_AA{0,  0};
constexpr KeyAddr addr_AB{0,  1};
constexpr KeyAddr addr_AC{0,  2};
constexpr KeyAddr addr_AD{0,  3};
constexpr KeyAddr addr_AE{0,  4};
constexpr KeyAddr addr_AF{0,  5};
constexpr KeyAddr addr_AG{0,  6};
constexpr KeyAddr addr_AH{0,  7};
constexpr KeyAddr addr_AI{0,  8};
constexpr KeyAddr addr_AJ{0,  9};
constexpr KeyAddr addr_AK{0, 10};
constexpr KeyAddr addr_AL{0, 11};
constexpr KeyAddr addr_AM{0, 12};
constexpr KeyAddr addr_AN{0, 13};
constexpr KeyAddr addr_AO{0, 14};
constexpr KeyAddr addr_AP{0, 15};
constexpr KeyAddr addr_BA{1,  0};
constexpr KeyAddr addr_BB{1,  1};
constexpr KeyAddr addr_BC{1,  2};
constexpr KeyAddr addr_BD{1,  3};
constexpr KeyAddr addr_BE{1,  4};
constexpr KeyAddr addr_BF{1,  5};
constexpr KeyAddr addr_BG{1,  6};
constexpr KeyAddr addr_BH{1,  7};
constexpr KeyAddr addr_BI{1,  8};
constexpr KeyAddr addr_BJ{1,  9};
constexpr KeyAddr addr_BK{1, 10};
constexpr KeyAddr addr_BL{1, 11};
constexpr KeyAddr addr_BM{1, 12};
constexpr KeyAddr addr_BN{1, 13};
constexpr KeyAddr addr_BO{1, 14};
constexpr KeyAddr addr_BP{1, 15};
constexpr KeyAddr addr_CA{2,  0};
constexpr KeyAddr addr_CB{2,  1};
constexpr KeyAddr addr_CC{2,  2};
constexpr KeyAddr addr_CD{2,  3};
constexpr KeyAddr addr_CE{2,  4};
constexpr KeyAddr addr_CF{2,  5};
constexpr KeyAddr addr_CG{2,  6};
constexpr KeyAddr addr_CH{2,  7};
constexpr KeyAddr addr_CI{2,  8};
constexpr KeyAddr addr_CJ{2,  9};
constexpr KeyAddr addr_CK{2, 10};
constexpr KeyAddr addr_CL{2, 11};
constexpr KeyAddr addr_CM{2, 12};
constexpr KeyAddr addr_CN{2, 13};
constexpr KeyAddr addr_CO{2, 14};
constexpr KeyAddr addr_CP{2, 15};
constexpr KeyAddr addr_DA{3,  0};
constexpr KeyAddr addr_DB{3,  1};
constexpr KeyAddr addr_DC{3,  2};
constexpr KeyAddr addr_DD{3,  3};
constexpr KeyAddr addr_DE{3,  4};
constexpr KeyAddr addr_DF{3,  5};
constexpr KeyAddr addr_DG{3,  6};
constexpr KeyAddr addr_DH{3,  7};
constexpr KeyAddr addr_DI{3,  8};
constexpr KeyAddr addr_DJ{3,  9};
constexpr KeyAddr addr_DK{3, 10};
constexpr KeyAddr addr_DL{3, 11};
constexpr KeyAddr addr_DM{3, 12};
constexpr KeyAddr addr_DN{3, 13};
constexpr KeyAddr addr_DO{3, 14};
constexpr KeyAddr addr_DP{3, 15};

namespace keymap {

class KeymapDefaults {
 public:
  // Layer 0
  static constexpr Key key_0AA = ___;
  static constexpr Key key_0AB = ___;
  static constexpr Key key_0AC = ___;
  static constexpr Key key_0AD = ___;
  static constexpr Key key_0AE = ___;
  static constexpr Key key_0AF = ___;
  static constexpr Key key_0AG = ___;
  static constexpr Key key_0AH = ___;
  static constexpr Key key_0AI = ___;
  static constexpr Key key_0AJ = ___;
  static constexpr Key key_0AK = ___;
  static constexpr Key key_0AL = ___;
  static constexpr Key key_0AM = ___;
  static constexpr Key key_0AN = ___;
  static constexpr Key key_0AO = ___;
  static constexpr Key key_0AP = ___;
  static constexpr Key key_0BA = ___;
  static constexpr Key key_0BB = ___;
  static constexpr Key key_0BC = ___;
  static constexpr Key key_0BD = ___;
  static constexpr Key key_0BE = ___;
  static constexpr Key key_0BF = ___;
  static constexpr Key key_0BG = ___;
  static constexpr Key key_0BH = ___;
  static constexpr Key key_0BI = ___;
  static constexpr Key key_0BJ = ___;
  static constexpr Key key_0BK = ___;
  static constexpr Key key_0BL = ___;
  static constexpr Key key_0BM = ___;
  static constexpr Key key_0BN = ___;
  static constexpr Key key_0BO = ___;
  static constexpr Key key_0BP = ___;
  static constexpr Key key_0CA = ___;
  static constexpr Key key_0CB = ___;
  static constexpr Key key_0CC = ___;
  static constexpr Key key_0CD = ___;
  static constexpr Key key_0CE = ___;
  static constexpr Key key_0CF = ___;
  static constexpr Key key_0CG = ___;
  static constexpr Key key_0CH = ___;
  static constexpr Key key_0CI = ___;
  static constexpr Key key_0CJ = ___;
  static constexpr Key key_0CK = ___;
  static constexpr Key key_0CL = ___;
  static constexpr Key key_0CM = ___;
  static constexpr Key key_0CN = ___;
  static constexpr Key key_0CO = ___;
  static constexpr Key key_0CP = ___;
  static constexpr Key key_0DA = ___;
  static constexpr Key key_0DB = ___;
  static constexpr Key key_0DC = ___;
  static constexpr Key key_0DD = ___;
  static constexpr Key key_0DE = ___;
  static constexpr Key key_0DF = ___;
  static constexpr Key key_0DG = ___;
  static constexpr Key key_0DH = ___;
  static constexpr Key key_0DI = ___;
  static constexpr Key key_0DJ = ___;
  static constexpr Key key_0DK = ___;
  static constexpr Key key_0DL = ___;
  static constexpr Key key_0DM = ___;
  static constexpr Key key_0DN = ___;
  static constexpr Key key_0DO = ___;
  static constexpr Key key_0DP = ___;
  // Layer 1
  static constexpr Key key_1AA = ___;
  static constexpr Key key_1AB = ___;
  static constexpr Key key_1AC = ___;
  static constexpr Key key_1AD = ___;
  static constexpr Key key_1AE = ___;
  static constexpr Key key_1AF = ___;
  static constexpr Key key_1AG = ___;
  static constexpr Key key_1AH = ___;
  static constexpr Key key_1AI = ___;
  static constexpr Key key_1AJ = ___;
  static constexpr Key key_1AK = ___;
  static constexpr Key key_1AL = ___;
  static constexpr Key key_1AM = ___;
  static constexpr Key key_1AN = ___;
  static constexpr Key key_1AO = ___;
  static constexpr Key key_1AP = ___;
  static constexpr Key key_1BA = ___;
  static constexpr Key key_1BB = ___;
  static constexpr Key key_1BC = ___;
  static constexpr Key key_1BD = ___;
  static constexpr Key key_1BE = ___;
  static constexpr Key key_1BF = ___;
  static constexpr Key key_1BG = ___;
  static constexpr Key key_1BH = ___;
  static constexpr Key key_1BI = ___;
  static constexpr Key key_1BJ = ___;
  static constexpr Key key_1BK = ___;
  static constexpr Key key_1BL = ___;
  static constexpr Key key_1BM = ___;
  static constexpr Key key_1BN = ___;
  static constexpr Key key_1BO = ___;
  static constexpr Key key_1BP = ___;
  static constexpr Key key_1CA = ___;
  static constexpr Key key_1CB = ___;
  static constexpr Key key_1CC = ___;
  static constexpr Key key_1CD = ___;
  static constexpr Key key_1CE = ___;
  static constexpr Key key_1CF = ___;
  static constexpr Key key_1CG = ___;
  static constexpr Key key_1CH = ___;
  static constexpr Key key_1CI = ___;
  static constexpr Key key_1CJ = ___;
  static constexpr Key key_1CK = ___;
  static constexpr Key key_1CL = ___;
  static constexpr Key key_1CM = ___;
  static constexpr Key key_1CN = ___;
  static constexpr Key key_1CO = ___;
  static constexpr Key key_1CP = ___;
  static constexpr Key key_1DA = ___;
  static constexpr Key key_1DB = ___;
  static constexpr Key key_1DC = ___;
  static constexpr Key key_1DD = ___;
  static constexpr Key key_1DE = ___;
  static constexpr Key key_1DF = ___;
  static constexpr Key key_1DG = ___;
  static constexpr Key key_1DH = ___;
  static constexpr Key key_1DI = ___;
  static constexpr Key key_1DJ = ___;
  static constexpr Key key_1DK = ___;
  static constexpr Key key_1DL = ___;
  static constexpr Key key_1DM = ___;
  static constexpr Key key_1DN = ___;
  static constexpr Key key_1DO = ___;
  static constexpr Key key_1DP = ___;
  // Layer 2
  static constexpr Key key_2AA = ___;
  static constexpr Key key_2AB = ___;
  static constexpr Key key_2AC = ___;
  static constexpr Key key_2AD = ___;
  static constexpr Key key_2AE = ___;
  static constexpr Key key_2AF = ___;
  static constexpr Key key_2AG = ___;
  static constexpr Key key_2AH = ___;
  static constexpr Key key_2AI = ___;
  static constexpr Key key_2AJ = ___;
  static constexpr Key key_2AK = ___;
  static constexpr Key key_2AL = ___;
  static constexpr Key key_2AM = ___;
  static constexpr Key key_2AN = ___;
  static constexpr Key key_2AO = ___;
  static constexpr Key key_2AP = ___;
  static constexpr Key key_2BA = ___;
  static constexpr Key key_2BB = ___;
  static constexpr Key key_2BC = ___;
  static constexpr Key key_2BD = ___;
  static constexpr Key key_2BE = ___;
  static constexpr Key key_2BF = ___;
  static constexpr Key key_2BG = ___;
  static constexpr Key key_2BH = ___;
  static constexpr Key key_2BI = ___;
  static constexpr Key key_2BJ = ___;
  static constexpr Key key_2BK = ___;
  static constexpr Key key_2BL = ___;
  static constexpr Key key_2BM = ___;
  static constexpr Key key_2BN = ___;
  static constexpr Key key_2BO = ___;
  static constexpr Key key_2BP = ___;
  static constexpr Key key_2CA = ___;
  static constexpr Key key_2CB = ___;
  static constexpr Key key_2CC = ___;
  static constexpr Key key_2CD = ___;
  static constexpr Key key_2CE = ___;
  static constexpr Key key_2CF = ___;
  static constexpr Key key_2CG = ___;
  static constexpr Key key_2CH = ___;
  static constexpr Key key_2CI = ___;
  static constexpr Key key_2CJ = ___;
  static constexpr Key key_2CK = ___;
  static constexpr Key key_2CL = ___;
  static constexpr Key key_2CM = ___;
  static constexpr Key key_2CN = ___;
  static constexpr Key key_2CO = ___;
  static constexpr Key key_2CP = ___;
  static constexpr Key key_2DA = ___;
  static constexpr Key key_2DB = ___;
  static constexpr Key key_2DC = ___;
  static constexpr Key key_2DD = ___;
  static constexpr Key key_2DE = ___;
  static constexpr Key key_2DF = ___;
  static constexpr Key key_2DG = ___;
  static constexpr Key key_2DH = ___;
  static constexpr Key key_2DI = ___;
  static constexpr Key key_2DJ = ___;
  static constexpr Key key_2DK = ___;
  static constexpr Key key_2DL = ___;
  static constexpr Key key_2DM = ___;
  static constexpr Key key_2DN = ___;
  static constexpr Key key_2DO = ___;
  static constexpr Key key_2DP = ___;
  // Layer 3
  static constexpr Key key_3AA = ___;
  static constexpr Key key_3AB = ___;
  static constexpr Key key_3AC = ___;
  static constexpr Key key_3AD = ___;
  static constexpr Key key_3AE = ___;
  static constexpr Key key_3AF = ___;
  static constexpr Key key_3AG = ___;
  static constexpr Key key_3AH = ___;
  static constexpr Key key_3AI = ___;
  static constexpr Key key_3AJ = ___;
  static constexpr Key key_3AK = ___;
  static constexpr Key key_3AL = ___;
  static constexpr Key key_3AM = ___;
  static constexpr Key key_3AN = ___;
  static constexpr Key key_3AO = ___;
  static constexpr Key key_3AP = ___;
  static constexpr Key key_3BA = ___;
  static constexpr Key key_3BB = ___;
  static constexpr Key key_3BC = ___;
  static constexpr Key key_3BD = ___;
  static constexpr Key key_3BE = ___;
  static constexpr Key key_3BF = ___;
  static constexpr Key key_3BG = ___;
  static constexpr Key key_3BH = ___;
  static constexpr Key key_3BI = ___;
  static constexpr Key key_3BJ = ___;
  static constexpr Key key_3BK = ___;
  static constexpr Key key_3BL = ___;
  static constexpr Key key_3BM = ___;
  static constexpr Key key_3BN = ___;
  static constexpr Key key_3BO = ___;
  static constexpr Key key_3BP = ___;
  static constexpr Key key_3CA = ___;
  static constexpr Key key_3CB = ___;
  static constexpr Key key_3CC = ___;
  static constexpr Key key_3CD = ___;
  static constexpr Key key_3CE = ___;
  static constexpr Key key_3CF = ___;
  static constexpr Key key_3CG = ___;
  static constexpr Key key_3CH = ___;
  static constexpr Key key_3CI = ___;
  static constexpr Key key_3CJ = ___;
  static constexpr Key key_3CK = ___;
  static constexpr Key key_3CL = ___;
  static constexpr Key key_3CM = ___;
  static constexpr Key key_3CN = ___;
  static constexpr Key key_3CO = ___;
  static constexpr Key key_3CP = ___;
  static constexpr Key key_3DA = ___;
  static constexpr Key key_3DB = ___;
  static constexpr Key key_3DC = ___;
  static constexpr Key key_3DD = ___;
  static constexpr Key key_3DE = ___;
  static constexpr Key key_3DF = ___;
  static constexpr Key key_3DG = ___;
  static constexpr Key key_3DH = ___;
  static constexpr Key key_3DI = ___;
  static constexpr Key key_3DJ = ___;
  static constexpr Key key_3DK = ___;
  static constexpr Key key_3DL = ___;
  static constexpr Key key_3DM = ___;
  static constexpr Key key_3DN = ___;
  static constexpr Key key_3DO = ___;
  static constexpr Key key_3DP = ___;
};

}  // namespace keymap
}  // namespace testing
}  // namespace kaleidoscope
