/* Kaleidoscope - Firmware for computer input devices
 * Copyright (C) 2013-2019  Keyboard.io, Inc.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "kaleidoscope/host_keymap/linux.h"

// This file was autogenerated by host_keymap.
// Its content is based on information provided by the XKB X11 system
// collected with the extraordinary libxkbcommon.

// layout: apl
// variant: dyalog

#define _HOST_KEYMAP_ASCII(OP) \
   OP('
', Key_KeypadEnter) /* XKB_KEY_KP_Enter, Enter  */ \
OP('!', LSHIFT(Key_Minus)) /* U+0021, XKB_KEY_exclam, EXCLAMATION MARK */ \
OP('\'', Key_K) /* U+0027, XKB_KEY_apostrophe, APOSTROPHE */ \
OP('*', Key_P) /* U+002a, XKB_KEY_asterisk, ASTERISK */ \
OP('+', LSHIFT(Key_KeypadAdd)) /* XKB_KEY_KP_Add */ \
OP('-', LSHIFT(Key_KeypadSubtract)) /* XKB_KEY_KP_Subtract */ \
OP('.', LSHIFT(Key_KeypadDot)) /* XKB_KEY_KP_Decimal */ \
OP('/', LSHIFT(Key_KeypadDivide)) /* XKB_KEY_KP_Divide */ \
OP('0', LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
OP('1', LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
OP('2', LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
OP('3', LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
OP('4', LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
OP('5', LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
OP('6', LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
OP('7', LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
OP('8', LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
OP('9', LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
OP('<', Key_3) /* U+003c, XKB_KEY_less, LESS-THAN SIGN */ \
OP('=', Key_5) /* U+003d, XKB_KEY_equal, EQUALS SIGN */ \
OP('>', Key_7) /* U+003e, XKB_KEY_greater, GREATER-THAN SIGN */ \
OP('?', Key_Q) /* U+003f, XKB_KEY_question, QUESTION MARK */ \
OP('_', Key_F) /* U+005f, XKB_KEY_underscore, LOW LINE */ \
OP('|', Key_M) /* U+007c, XKB_KEY_bar, VERTICAL LINE */ \
OP('~', Key_T) /* U+007e, XKB_KEY_asciitilde, TILDE */ \

#define _HOST_KEYMAP_UNICODE(OP) \
   OP(L'
', Key_KeypadEnter) /* XKB_KEY_KP_Enter, Enter  */ \
OP(L'!', LSHIFT(Key_Minus)) /* U+0021, XKB_KEY_exclam, EXCLAMATION MARK */ \
OP(L'\'', Key_K) /* U+0027, XKB_KEY_apostrophe, APOSTROPHE */ \
OP(L'*', Key_P) /* U+002a, XKB_KEY_asterisk, ASTERISK */ \
OP(L'+', LSHIFT(Key_KeypadAdd)) /* XKB_KEY_KP_Add */ \
OP(L'-', LSHIFT(Key_KeypadSubtract)) /* XKB_KEY_KP_Subtract */ \
OP(L'.', LSHIFT(Key_KeypadDot)) /* XKB_KEY_KP_Decimal */ \
OP(L'/', LSHIFT(Key_KeypadDivide)) /* XKB_KEY_KP_Divide */ \
OP(L'0', LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
OP(L'1', LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
OP(L'2', LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
OP(L'3', LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
OP(L'4', LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
OP(L'5', LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
OP(L'6', LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
OP(L'7', LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
OP(L'8', LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
OP(L'9', LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
OP(L'<', Key_3) /* U+003c, XKB_KEY_less, LESS-THAN SIGN */ \
OP(L'=', Key_5) /* U+003d, XKB_KEY_equal, EQUALS SIGN */ \
OP(L'>', Key_7) /* U+003e, XKB_KEY_greater, GREATER-THAN SIGN */ \
OP(L'?', Key_Q) /* U+003f, XKB_KEY_question, QUESTION MARK */ \
OP(L'_', Key_F) /* U+005f, XKB_KEY_underscore, LOW LINE */ \
OP(L'|', Key_M) /* U+007c, XKB_KEY_bar, VERTICAL LINE */ \
OP(L'~', Key_T) /* U+007e, XKB_KEY_asciitilde, TILDE */ \
OP(L'¨', Key_1) /* U+00a8, XKB_KEY_diaeresis, DIAERESIS */ \
OP(L'¯', Key_2) /* U+00af, XKB_KEY_macron, MACRON */ \
OP(L'×', Key_Minus) /* U+00d7, XKB_KEY_multiply, MULTIPLICATION SIGN */ \
OP(L'÷', Key_Equals) /* U+00f7, XKB_KEY_division, DIVISION SIGN */ \
OP(L'←', Key_LeftBracket) \
OP(L'↑', Key_Y) \
OP(L'→', Key_RightBracket) \
OP(L'↓', Key_U) \
OP(L'∆', Key_H) \
OP(L'∇', Key_G) \
OP(L'∊', Key_E) \
OP(L'∘', Key_J) \
OP(L'∥', LSHIFT(Key_M)) \
OP(L'∧', Key_0) \
OP(L'∨', Key_9) \
OP(L'∩', Key_C) \
OP(L'∪', Key_V) \
OP(L'≠', Key_8) \
OP(L'≡', LSHIFT(Key_Semicolon)) \
OP(L'≢', LSHIFT(Key_Quote)) /* U+2262, XKB_KEY_notidentical, NOT IDENTICAL TO */ \
OP(L'≤', Key_4) \
OP(L'≥', Key_6) \
OP(L'⊂', Key_Z) \
OP(L'⊃', Key_X) \
OP(L'⊆', LSHIFT(Key_Z)) \
OP(L'⊖', LSHIFT(Key_7)) \
OP(L'⊢', Key_NonUsPound) \
OP(L'⊣', LSHIFT(Key_NonUsPound)) \
OP(L'⊤', Key_N) \
OP(L'⊥', Key_B) \
OP(L'⋄', Key_Backtick) \
OP(L'⌈', Key_S) \
OP(L'⌊', Key_D) \
OP(L'⌶', LSHIFT(Key_1)) \
OP(L'⌷', LSHIFT(Key_L)) \
OP(L'⌸', LSHIFT(Key_K)) \
OP(L'⌹', LSHIFT(Key_Equals)) \
OP(L'⌺', LSHIFT(Key_Backtick)) \
OP(L'⌽', LSHIFT(Key_5)) \
OP(L'⌾', LSHIFT(Key_R)) \
OP(L'⌿', Key_Slash) \
OP(L'⍀', Key_Period) \
OP(L'⍉', LSHIFT(Key_6)) \
OP(L'⍋', LSHIFT(Key_4)) \
OP(L'⍎', Key_Semicolon) \
OP(L'⍒', LSHIFT(Key_3)) \
OP(L'⍕', Key_Quote) \
OP(L'⍙', LSHIFT(Key_Period)) \
OP(L'⍝', Key_Comma) \
OP(L'⍞', LSHIFT(Key_LeftBracket)) \
OP(L'⍟', LSHIFT(Key_8)) \
OP(L'⍠', LSHIFT(Key_Slash)) \
OP(L'⍡', LSHIFT(Key_N)) \
OP(L'⍢', LSHIFT(Key_G)) \
OP(L'⍣', LSHIFT(Key_P)) \
OP(L'⍤', LSHIFT(Key_J)) \
OP(L'⍥', LSHIFT(Key_O)) \
OP(L'⍨', LSHIFT(Key_T)) \
OP(L'⍪', LSHIFT(Key_Comma)) \
OP(L'⍫', LSHIFT(Key_2)) \
OP(L'⍬', LSHIFT(Key_RightBracket)) \
OP(L'⍭', LSHIFT(Key_B)) \
OP(L'⍰', LSHIFT(Key_Q)) \
OP(L'⍱', LSHIFT(Key_9)) \
OP(L'⍲', LSHIFT(Key_0)) \
OP(L'⍳', Key_I) \
OP(L'⍴', Key_R) \
OP(L'⍵', Key_W) \
OP(L'⍷', LSHIFT(Key_E)) \
OP(L'⍸', LSHIFT(Key_I)) \
OP(L'⍺', Key_A) \
OP(L'⎕', Key_L) \
OP(L'─', Key_Keypad0) \
OP(L'│', Key_KeypadDot) \
OP(L'┌', Key_Keypad7) \
OP(L'┐', Key_Keypad9) \
OP(L'└', Key_Keypad1) \
OP(L'┘', Key_Keypad3) \
OP(L'├', Key_Keypad4) \
OP(L'┤', Key_Keypad6) \
OP(L'┬', Key_Keypad8) \
OP(L'┴', Key_Keypad2) \
OP(L'┼', Key_Keypad5) \
OP(L'○', Key_O) \
OP(L'', Key_Escape) \
OP(L'', Key_Tab) \
OP(L'', LSHIFT(Key_Tab)) \
OP(L'', Key_PageUp) \
OP(L'', Key_PageDown) \
OP(L'', Key_End) \
OP(L'', Key_Home) \
OP(L'', LSHIFT(Key_PageUp)) \
OP(L'', LSHIFT(Key_PageDown)) \
OP(L'', LSHIFT(Key_End)) \
OP(L'', LSHIFT(Key_Home)) \
OP(L'', LSHIFT(Key_Delete)) \
OP(L'', LSHIFT(Key_Insert)) \
OP(L'', Key_KeypadDivide) \
OP(L'', Key_KeypadMultiply) \
OP(L'', Key_Delete) \
OP(L'', Key_Insert) \
OP(L'', Key_DownArrow) \
OP(L'', Key_UpArrow) \
OP(L'', Key_F11) \
OP(L'', Key_RightArrow) \
OP(L'', Key_LeftArrow) \
OP(L'', Key_Enter) \
OP(L'', LSHIFT(Key_Enter)) \
OP(L'', Key_KeypadSubtract) \
OP(L'', LSHIFT(Key_LeftArrow)) \
OP(L'', Key_Backspace) \
OP(L'', LSHIFT(Key_RightArrow)) \
OP(L'', LSHIFT(Key_Backspace)) \
OP(L'', Key_KeypadAdd) \
OP(L'', Key_Spacebar) \
OP(L'', LSHIFT(Key_Spacebar)) \

#define _HOST_KEYMAP_NON_PRINTABLE(OP) \
   OP(XKB_KEY_Alt_L, Key_LeftAlt) /* XKB_KEY_Alt_L, Left alt  */ \
   OP(XKB_KEY_Alt_R, Key_RightAlt) /* XKB_KEY_Alt_R, Right alt  */ \
   OP(XKB_KEY_Break, LCTRL(Key_Pause)) /* XKB_KEY_Break */ \
   OP(XKB_KEY_Caps_Lock, Key_CapsLock) /* XKB_KEY_Caps_Lock, Caps lock  */ \
   OP(XKB_KEY_Control_L, Key_LeftControl) /* XKB_KEY_Control_L, Left control  */ \
   OP(XKB_KEY_Control_R, Key_RightControl) /* XKB_KEY_Control_R, Right control  */ \
   OP(XKB_KEY_F1, Key_F1) /* XKB_KEY_F1 */ \
   OP(XKB_KEY_F10, Key_F10) /* XKB_KEY_F10 */ \
   OP(XKB_KEY_F12, Key_F12) /* XKB_KEY_F12 */ \
   OP(XKB_KEY_F2, Key_F2) /* XKB_KEY_F2 */ \
   OP(XKB_KEY_F3, Key_F3) /* XKB_KEY_F3 */ \
   OP(XKB_KEY_F4, Key_F4) /* XKB_KEY_F4 */ \
   OP(XKB_KEY_F5, Key_F5) /* XKB_KEY_F5 */ \
   OP(XKB_KEY_F6, Key_F6) /* XKB_KEY_F6 */ \
   OP(XKB_KEY_F7, Key_F7) /* XKB_KEY_F7 */ \
   OP(XKB_KEY_F8, Key_F8) /* XKB_KEY_F8 */ \
   OP(XKB_KEY_F9, Key_F9) /* XKB_KEY_F9 */ \
   OP(XKB_KEY_KP_0, LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
   OP(XKB_KEY_KP_1, LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
   OP(XKB_KEY_KP_2, LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
   OP(XKB_KEY_KP_3, LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
   OP(XKB_KEY_KP_4, LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
   OP(XKB_KEY_KP_5, LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
   OP(XKB_KEY_KP_6, LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
   OP(XKB_KEY_KP_7, LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
   OP(XKB_KEY_KP_8, LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
   OP(XKB_KEY_KP_9, LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
   OP(XKB_KEY_KP_Add, LSHIFT(Key_KeypadAdd)) /* XKB_KEY_KP_Add */ \
   OP(XKB_KEY_KP_Decimal, LSHIFT(Key_KeypadDot)) /* XKB_KEY_KP_Decimal */ \
   OP(XKB_KEY_KP_Divide, LSHIFT(Key_KeypadDivide)) /* XKB_KEY_KP_Divide */ \
   OP(XKB_KEY_KP_Enter, Key_KeypadEnter) /* XKB_KEY_KP_Enter, Enter  */ \
   OP(XKB_KEY_KP_Multiply, LSHIFT(Key_KeypadMultiply)) /* XKB_KEY_KP_Multiply */ \
   OP(XKB_KEY_KP_Subtract, LSHIFT(Key_KeypadSubtract)) /* XKB_KEY_KP_Subtract */ \
   OP(XKB_KEY_Menu, Key_PcApplication) /* XKB_KEY_Menu */ \
   OP(XKB_KEY_Meta_L, LSHIFT(Key_LeftAlt)) /* XKB_KEY_Meta_L, Left meta  */ \
   OP(XKB_KEY_Meta_R, LSHIFT(Key_RightAlt)) /* XKB_KEY_Meta_R, Right meta  */ \
   OP(XKB_KEY_Num_Lock, Key_KeypadNumLock) /* XKB_KEY_Num_Lock */ \
   OP(XKB_KEY_Pause, Key_Pause) /* XKB_KEY_Pause, Pause, hold  */ \
   OP(XKB_KEY_Print, Key_PrintScreen) /* XKB_KEY_Print */ \
   OP(XKB_KEY_Scroll_Lock, Key_ScrollLock) /* XKB_KEY_Scroll_Lock */ \
   OP(XKB_KEY_Shift_L, Key_LeftShift) /* XKB_KEY_Shift_L, Left shift  */ \
   OP(XKB_KEY_Shift_R, Key_RightShift) /* XKB_KEY_Shift_R, Right shift  */ \
   OP(XKB_KEY_Super_L, Key_LeftGui) /* XKB_KEY_Super_L, Left super  */ \
   OP(XKB_KEY_Super_R, Key_RightGui) /* XKB_KEY_Super_R, Right super  */ \
   OP(XKB_KEY_Sys_Req, LALT(Key_PrintScreen)) /* XKB_KEY_Sys_Req */ \
   OP(XKB_KEY_XF86ClearGrab, LCTRL(LALT(Key_KeypadMultiply))) /* XKB_KEY_XF86ClearGrab, kill application with grab  */ \
   OP(XKB_KEY_XF86Next_VMode, LCTRL(LALT(Key_KeypadAdd))) /* XKB_KEY_XF86Next_VMode, next video mode available   */ \
   OP(XKB_KEY_XF86Prev_VMode, LCTRL(LALT(Key_KeypadSubtract))) /* XKB_KEY_XF86Prev_VMode, prev. video mode available  */ \
   OP(XKB_KEY_XF86Switch_VT_1, LCTRL(LALT(Key_F1))) /* XKB_KEY_XF86Switch_VT_1 */ \
   OP(XKB_KEY_XF86Switch_VT_10, LCTRL(LALT(Key_F10))) /* XKB_KEY_XF86Switch_VT_10 */ \
   OP(XKB_KEY_XF86Switch_VT_11, LCTRL(LALT(Key_F11))) /* XKB_KEY_XF86Switch_VT_11 */ \
   OP(XKB_KEY_XF86Switch_VT_12, LCTRL(LALT(Key_F12))) /* XKB_KEY_XF86Switch_VT_12 */ \
   OP(XKB_KEY_XF86Switch_VT_2, LCTRL(LALT(Key_F2))) /* XKB_KEY_XF86Switch_VT_2 */ \
   OP(XKB_KEY_XF86Switch_VT_3, LCTRL(LALT(Key_F3))) /* XKB_KEY_XF86Switch_VT_3 */ \
   OP(XKB_KEY_XF86Switch_VT_4, LCTRL(LALT(Key_F4))) /* XKB_KEY_XF86Switch_VT_4 */ \
   OP(XKB_KEY_XF86Switch_VT_5, LCTRL(LALT(Key_F5))) /* XKB_KEY_XF86Switch_VT_5 */ \
   OP(XKB_KEY_XF86Switch_VT_6, LCTRL(LALT(Key_F6))) /* XKB_KEY_XF86Switch_VT_6 */ \
   OP(XKB_KEY_XF86Switch_VT_7, LCTRL(LALT(Key_F7))) /* XKB_KEY_XF86Switch_VT_7 */ \
   OP(XKB_KEY_XF86Switch_VT_8, LCTRL(LALT(Key_F8))) /* XKB_KEY_XF86Switch_VT_8 */ \
   OP(XKB_KEY_XF86Switch_VT_9, LCTRL(LALT(Key_F9))) /* XKB_KEY_XF86Switch_VT_9 */ \
   OP(XKB_KEY_XF86Ungrab, LCTRL(LALT(Key_KeypadDivide))) /* XKB_KEY_XF86Ungrab, force ungrab                */ \
   OP(XKB_KEY_apostrophe, Key_K) /* XKB_KEY_quoteright, deprecated  */ \
   OP(XKB_KEY_asciitilde, Key_T) \
   OP(XKB_KEY_asterisk, Key_P) \
   OP(XKB_KEY_bar, Key_M) \
   OP(XKB_KEY_diaeresis, Key_1) \
   OP(XKB_KEY_division, Key_Equals) \
   OP(XKB_KEY_equal, Key_5) \
   OP(XKB_KEY_exclam, LSHIFT(Key_Minus)) \
   OP(XKB_KEY_greater, Key_7) \
   OP(XKB_KEY_less, Key_3) \
   OP(XKB_KEY_macron, Key_2) \
   OP(XKB_KEY_multiply, Key_Minus) \
   OP(XKB_KEY_notidentical, LSHIFT(Key_Quote)) \
   OP(XKB_KEY_question, Key_Q) \
   OP(XKB_KEY_underscore, Key_F) \


namespace kaleidoscope {
namespace host_keymap {
namespace linux {
namespace apl {
namespace dyalog {

HOST_KEYMAP_LINUX(
  _HOST_KEYMAP_ASCII,
  _HOST_KEYMAP_UNICODE,
  _HOST_KEYMAP_NON_PRINTABLE
)

} // namespace dyalog
} // namespace apl
} // namespace linux
} // namespace host_keymap
} // namespace kaleidoscope

#undef _HOST_KEYMAP_ASCII
#undef _HOST_KEYMAP_UNICODE
#undef _HOST_KEYMAP_NON_PRINTABLE

