/* Kaleidoscope - Firmware for computer input devices
 * Copyright (C) 2013-2019  Keyboard.io, Inc.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation, version 3.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "kaleidoscope/host_keymap/linux.h"

// This file was autogenerated by host_keymap.
// Its content is based on information provided by the XKB X11 system
// collected with the extraordinary libxkbcommon.

// layout: th
// variant: standard

#define _HOST_KEYMAP_ASCII(OP) \
   OP('\b', Key_Backspace) /* XKB_KEY_BackSpace, Back space, back char  */ \
   OP('\t', Key_Tab) /* XKB_KEY_Tab */ \
   OP('\r', Key_Enter) /* XKB_KEY_Return, Return, enter  */ \
   OP('\e', Key_Escape) /* XKB_KEY_Escape */ \
   OP(' ', Key_Spacebar) /* U+0020, XKB_KEY_space, SPACE */ \
   OP('"', LSHIFT(Key_W)) /* U+0022, XKB_KEY_quotedbl, QUOTATION MARK */ \
   OP('%', LSHIFT(Key_Backtick)) /* U+0025, XKB_KEY_percent, PERCENT SIGN */ \
   OP('(', LSHIFT(Key_Z)) /* U+0028, XKB_KEY_parenleft, LEFT PARENTHESIS */ \
   OP(')', LSHIFT(Key_X)) /* U+0029, XKB_KEY_parenright, RIGHT PARENTHESIS */ \
   OP('*', Key_KeypadMultiply) /* XKB_KEY_KP_Multiply */ \
   OP('+', Key_KeypadAdd) /* XKB_KEY_KP_Add */ \
   OP(',', LSHIFT(Key_RightBracket)) /* U+002c, XKB_KEY_comma, COMMA */ \
   OP('-', Key_3) /* U+002d, XKB_KEY_minus, HYPHEN-MINUS */ \
   OP('.', LSHIFT(Key_Quote)) /* U+002e, XKB_KEY_period, FULL STOP */ \
   OP('/', Key_2) /* U+002f, XKB_KEY_slash, SOLIDUS */ \
   OP('0', LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
   OP('1', LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
   OP('2', LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
   OP('3', LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
   OP('4', LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
   OP('5', LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
   OP('6', LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
   OP('7', LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
   OP('8', LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
   OP('9', LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
   OP('<', Key_NonUsBackslashAndPipe) /* U+003c, XKB_KEY_less, LESS-THAN SIGN */ \
   OP('>', LSHIFT(Key_NonUsBackslashAndPipe)) /* U+003e, XKB_KEY_greater, GREATER-THAN SIGN */ \
   OP('?', LSHIFT(Key_M)) /* U+003f, XKB_KEY_question, QUESTION MARK */ \
   OP('_', Key_Backtick) /* U+005f, XKB_KEY_underscore, LOW LINE */ \
   OP('', Key_Delete) /* XKB_KEY_Delete, Delete, rubout  */ \

#define _HOST_KEYMAP_UNICODE(OP) \
   OP(L'\b', Key_Backspace) /* XKB_KEY_BackSpace, Back space, back char  */ \
   OP(L'\t', Key_Tab) /* XKB_KEY_Tab */ \
   OP(L'\r', Key_Enter) /* XKB_KEY_Return, Return, enter  */ \
   OP(L'\e', Key_Escape) /* XKB_KEY_Escape */ \
   OP(L' ', Key_Spacebar) /* U+0020, XKB_KEY_space, SPACE */ \
   OP(L'"', LSHIFT(Key_W)) /* U+0022, XKB_KEY_quotedbl, QUOTATION MARK */ \
   OP(L'%', LSHIFT(Key_Backtick)) /* U+0025, XKB_KEY_percent, PERCENT SIGN */ \
   OP(L'(', LSHIFT(Key_Z)) /* U+0028, XKB_KEY_parenleft, LEFT PARENTHESIS */ \
   OP(L')', LSHIFT(Key_X)) /* U+0029, XKB_KEY_parenright, RIGHT PARENTHESIS */ \
   OP(L'*', Key_KeypadMultiply) /* XKB_KEY_KP_Multiply */ \
   OP(L'+', Key_KeypadAdd) /* XKB_KEY_KP_Add */ \
   OP(L',', LSHIFT(Key_RightBracket)) /* U+002c, XKB_KEY_comma, COMMA */ \
   OP(L'-', Key_3) /* U+002d, XKB_KEY_minus, HYPHEN-MINUS */ \
   OP(L'.', LSHIFT(Key_Quote)) /* U+002e, XKB_KEY_period, FULL STOP */ \
   OP(L'/', Key_2) /* U+002f, XKB_KEY_slash, SOLIDUS */ \
   OP(L'0', LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
   OP(L'1', LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
   OP(L'2', LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
   OP(L'3', LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
   OP(L'4', LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
   OP(L'5', LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
   OP(L'6', LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
   OP(L'7', LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
   OP(L'8', LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
   OP(L'9', LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
   OP(L'<', Key_NonUsBackslashAndPipe) /* U+003c, XKB_KEY_less, LESS-THAN SIGN */ \
   OP(L'>', LSHIFT(Key_NonUsBackslashAndPipe)) /* U+003e, XKB_KEY_greater, GREATER-THAN SIGN */ \
   OP(L'?', LSHIFT(Key_M)) /* U+003f, XKB_KEY_question, QUESTION MARK */ \
   OP(L'_', Key_Backtick) /* U+005f, XKB_KEY_underscore, LOW LINE */ \
   OP(L'', Key_Delete) /* XKB_KEY_Delete, Delete, rubout  */ \
   OP(L'ก', Key_D) /* U+0e01, XKB_KEY_Thai_kokai, THAI CHARACTER KO KAI */ \
   OP(L'ข', Key_Minus) /* U+0e02, XKB_KEY_Thai_khokhai, THAI CHARACTER KHO KHAI */ \
   OP(L'ฃ', Key_NonUsPound) /* U+0e03, XKB_KEY_Thai_khokhuat, THAI CHARACTER KHO KHUAT */ \
   OP(L'ค', Key_8) /* U+0e04, XKB_KEY_Thai_khokhwai, THAI CHARACTER KHO KHWAI */ \
   OP(L'ฅ', LSHIFT(Key_NonUsPound)) /* U+0e05, XKB_KEY_Thai_khokhon, THAI CHARACTER KHO KHON */ \
   OP(L'ฆ', LSHIFT(Key_S)) /* U+0e06, XKB_KEY_Thai_khorakhang, THAI CHARACTER KHO RAKHANG */ \
   OP(L'ง', Key_Quote) /* U+0e07, XKB_KEY_Thai_ngongu, THAI CHARACTER NGO NGU */ \
   OP(L'จ', Key_0) /* U+0e08, XKB_KEY_Thai_chochan, THAI CHARACTER CHO CHAN */ \
   OP(L'ฉ', LSHIFT(Key_C)) /* U+0e09, XKB_KEY_Thai_choching, THAI CHARACTER CHO CHING */ \
   OP(L'ช', Key_Equals) /* U+0e0a, XKB_KEY_Thai_chochang, THAI CHARACTER CHO CHANG */ \
   OP(L'ซ', LSHIFT(Key_Semicolon)) /* U+0e0b, XKB_KEY_Thai_soso, THAI CHARACTER SO SO */ \
   OP(L'ฌ', LSHIFT(Key_G)) /* U+0e0c, XKB_KEY_Thai_chochoe, THAI CHARACTER CHO CHOE */ \
   OP(L'ญ', LSHIFT(Key_P)) /* U+0e0d, XKB_KEY_Thai_yoying, THAI CHARACTER YO YING */ \
   OP(L'ฎ', LSHIFT(Key_E)) /* U+0e0e, XKB_KEY_Thai_dochada, THAI CHARACTER DO CHADA */ \
   OP(L'ฏ', LSHIFT(Key_D)) /* U+0e0f, XKB_KEY_Thai_topatak, THAI CHARACTER TO PATAK */ \
   OP(L'ฐ', LSHIFT(Key_LeftBracket)) /* U+0e10, XKB_KEY_Thai_thothan, THAI CHARACTER THO THAN */ \
   OP(L'ฑ', LSHIFT(Key_R)) /* U+0e11, XKB_KEY_Thai_thonangmontho, THAI CHARACTER THO NANGMONTHO */ \
   OP(L'ฒ', LSHIFT(Key_Comma)) /* U+0e12, XKB_KEY_Thai_thophuthao, THAI CHARACTER THO PHUTHAO */ \
   OP(L'ณ', LSHIFT(Key_I)) /* U+0e13, XKB_KEY_Thai_nonen, THAI CHARACTER NO NEN */ \
   OP(L'ด', Key_F) /* U+0e14, XKB_KEY_Thai_dodek, THAI CHARACTER DO DEK */ \
   OP(L'ต', Key_9) /* U+0e15, XKB_KEY_Thai_totao, THAI CHARACTER TO TAO */ \
   OP(L'ถ', Key_5) /* U+0e16, XKB_KEY_Thai_thothung, THAI CHARACTER THO THUNG */ \
   OP(L'ท', Key_M) /* U+0e17, XKB_KEY_Thai_thothahan, THAI CHARACTER THO THAHAN */ \
   OP(L'ธ', LSHIFT(Key_T)) /* U+0e18, XKB_KEY_Thai_thothong, THAI CHARACTER THO THONG */ \
   OP(L'น', Key_O) /* U+0e19, XKB_KEY_Thai_nonu, THAI CHARACTER NO NU */ \
   OP(L'บ', Key_LeftBracket) /* U+0e1a, XKB_KEY_Thai_bobaimai, THAI CHARACTER BO BAIMAI */ \
   OP(L'ป', Key_X) /* U+0e1b, XKB_KEY_Thai_popla, THAI CHARACTER PO PLA */ \
   OP(L'ผ', Key_Z) /* U+0e1c, XKB_KEY_Thai_phophung, THAI CHARACTER PHO PHUNG */ \
   OP(L'ฝ', Key_Slash) /* U+0e1d, XKB_KEY_Thai_fofa, THAI CHARACTER FO FA */ \
   OP(L'พ', Key_R) /* U+0e1e, XKB_KEY_Thai_phophan, THAI CHARACTER PHO PHAN */ \
   OP(L'ฟ', Key_A) /* U+0e1f, XKB_KEY_Thai_fofan, THAI CHARACTER FO FAN */ \
   OP(L'ภ', Key_4) /* U+0e20, XKB_KEY_Thai_phosamphao, THAI CHARACTER PHO SAMPHAO */ \
   OP(L'ม', Key_Comma) /* U+0e21, XKB_KEY_Thai_moma, THAI CHARACTER MO MA */ \
   OP(L'ย', Key_P) /* U+0e22, XKB_KEY_Thai_yoyak, THAI CHARACTER YO YAK */ \
   OP(L'ร', Key_I) /* U+0e23, XKB_KEY_Thai_rorua, THAI CHARACTER RO RUA */ \
   OP(L'ฤ', LSHIFT(Key_A)) /* U+0e24, XKB_KEY_Thai_ru, THAI CHARACTER RU */ \
   OP(L'ล', Key_RightBracket) /* U+0e25, XKB_KEY_Thai_loling, THAI CHARACTER LO LING */ \
   OP(L'ฦ', LSHIFT(Key_Slash)) /* U+0e26, XKB_KEY_Thai_lu, THAI CHARACTER LU */ \
   OP(L'ว', Key_Semicolon) /* U+0e27, XKB_KEY_Thai_wowaen, THAI CHARACTER WO WAEN */ \
   OP(L'ศ', LSHIFT(Key_L)) /* U+0e28, XKB_KEY_Thai_sosala, THAI CHARACTER SO SALA */ \
   OP(L'ษ', LSHIFT(Key_K)) /* U+0e29, XKB_KEY_Thai_sorusi, THAI CHARACTER SO RUSI */ \
   OP(L'ส', Key_L) /* U+0e2a, XKB_KEY_Thai_sosua, THAI CHARACTER SO SUA */ \
   OP(L'ห', Key_S) /* U+0e2b, XKB_KEY_Thai_hohip, THAI CHARACTER HO HIP */ \
   OP(L'ฬ', LSHIFT(Key_Period)) /* U+0e2c, XKB_KEY_Thai_lochula, THAI CHARACTER LO CHULA */ \
   OP(L'อ', Key_V) /* U+0e2d, XKB_KEY_Thai_oang, THAI CHARACTER O ANG */ \
   OP(L'ฮ', LSHIFT(Key_V)) /* U+0e2e, XKB_KEY_Thai_honokhuk, THAI CHARACTER HO NOKHUK */ \
   OP(L'ฯ', LSHIFT(Key_O)) /* U+0e2f, XKB_KEY_Thai_paiyannoi, THAI CHARACTER PAIYANNOI */ \
   OP(L'ะ', Key_T) /* U+0e30, XKB_KEY_Thai_saraa, THAI CHARACTER SARA A */ \
   OP(L'ั', Key_Y) /* U+0e31, XKB_KEY_Thai_maihanakat, THAI CHARACTER MAI HAN-AKAT */ \
   OP(L'า', Key_K) /* U+0e32, XKB_KEY_Thai_saraaa, THAI CHARACTER SARA AA */ \
   OP(L'ำ', Key_E) /* U+0e33, XKB_KEY_Thai_saraam, THAI CHARACTER SARA AM */ \
   OP(L'ิ', Key_B) /* U+0e34, XKB_KEY_Thai_sarai, THAI CHARACTER SARA I */ \
   OP(L'ี', Key_U) /* U+0e35, XKB_KEY_Thai_saraii, THAI CHARACTER SARA II */ \
   OP(L'ึ', Key_7) /* U+0e36, XKB_KEY_Thai_saraue, THAI CHARACTER SARA UE */ \
   OP(L'ื', Key_N) /* U+0e37, XKB_KEY_Thai_sarauee, THAI CHARACTER SARA UEE */ \
   OP(L'ุ', Key_6) /* U+0e38, XKB_KEY_Thai_sarau, THAI CHARACTER SARA U */ \
   OP(L'ู', LSHIFT(Key_6)) /* U+0e39, XKB_KEY_Thai_sarauu, THAI CHARACTER SARA UU */ \
   OP(L'ฺ', LSHIFT(Key_B)) /* U+0e3a, XKB_KEY_Thai_phinthu, THAI CHARACTER PHINTHU */ \
   OP(L'฿', LSHIFT(Key_7)) /* U+0e3f, XKB_KEY_Thai_baht, THAI CURRENCY SYMBOL BAHT */ \
   OP(L'เ', Key_G) /* U+0e40, XKB_KEY_Thai_sarae, THAI CHARACTER SARA E */ \
   OP(L'แ', Key_C) /* U+0e41, XKB_KEY_Thai_saraae, THAI CHARACTER SARA AE */ \
   OP(L'โ', LSHIFT(Key_F)) /* U+0e42, XKB_KEY_Thai_sarao, THAI CHARACTER SARA O */ \
   OP(L'ใ', Key_Period) /* U+0e43, XKB_KEY_Thai_saraaimaimuan, THAI CHARACTER SARA AI MAIMUAN */ \
   OP(L'ไ', Key_W) /* U+0e44, XKB_KEY_Thai_saraaimaimalai, THAI CHARACTER SARA AI MAIMALAI */ \
   OP(L'ๅ', Key_1) /* U+0e45, XKB_KEY_Thai_lakkhangyao, THAI CHARACTER LAKKHANGYAO */ \
   OP(L'ๆ', Key_Q) /* U+0e46, XKB_KEY_Thai_maiyamok, THAI CHARACTER MAIYAMOK */ \
   OP(L'็', LSHIFT(Key_H)) /* U+0e47, XKB_KEY_Thai_maitaikhu, THAI CHARACTER MAITAIKHU */ \
   OP(L'่', Key_J) /* U+0e48, XKB_KEY_Thai_maiek, THAI CHARACTER MAI EK */ \
   OP(L'้', Key_H) /* U+0e49, XKB_KEY_Thai_maitho, THAI CHARACTER MAI THO */ \
   OP(L'๊', LSHIFT(Key_U)) /* U+0e4a, XKB_KEY_Thai_maitri, THAI CHARACTER MAI TRI */ \
   OP(L'๋', LSHIFT(Key_J)) /* U+0e4b, XKB_KEY_Thai_maichattawa, THAI CHARACTER MAI CHATTAWA */ \
   OP(L'์', LSHIFT(Key_N)) /* U+0e4c, XKB_KEY_Thai_thanthakhat, THAI CHARACTER THANTHAKHAT */ \
   OP(L'ํ', LSHIFT(Key_Y)) /* U+0e4d, XKB_KEY_Thai_nikhahit, THAI CHARACTER NIKHAHIT */ \
   OP(L'๐', LSHIFT(Key_Q)) /* U+0e50, XKB_KEY_Thai_leksun, THAI DIGIT ZERO */ \
   OP(L'๑', LSHIFT(Key_2)) /* U+0e51, XKB_KEY_Thai_leknung, THAI DIGIT ONE */ \
   OP(L'๒', LSHIFT(Key_3)) /* U+0e52, XKB_KEY_Thai_leksong, THAI DIGIT TWO */ \
   OP(L'๓', LSHIFT(Key_4)) /* U+0e53, XKB_KEY_Thai_leksam, THAI DIGIT THREE */ \
   OP(L'๔', LSHIFT(Key_5)) /* U+0e54, XKB_KEY_Thai_leksi, THAI DIGIT FOUR */ \
   OP(L'๕', LSHIFT(Key_8)) /* U+0e55, XKB_KEY_Thai_lekha, THAI DIGIT FIVE */ \
   OP(L'๖', LSHIFT(Key_9)) /* U+0e56, XKB_KEY_Thai_lekhok, THAI DIGIT SIX */ \
   OP(L'๗', LSHIFT(Key_0)) /* U+0e57, XKB_KEY_Thai_lekchet, THAI DIGIT SEVEN */ \
   OP(L'๘', LSHIFT(Key_Minus)) /* U+0e58, XKB_KEY_Thai_lekpaet, THAI DIGIT EIGHT */ \
   OP(L'๙', LSHIFT(Key_Equals)) /* U+0e59, XKB_KEY_Thai_lekkao, THAI DIGIT NINE */ \

#define _HOST_KEYMAP_NON_PRINTABLE(OP) \
   OP(XKB_KEY_Alt_L, Key_LeftAlt) /* XKB_KEY_Alt_L, Left alt  */ \
   OP(XKB_KEY_Alt_R, Key_RightAlt) /* XKB_KEY_Alt_R, Right alt  */ \
   OP(XKB_KEY_BackSpace, Key_Backspace) /* XKB_KEY_BackSpace, Back space, back char  */ \
   OP(XKB_KEY_Break, LCTRL(Key_Pause)) /* XKB_KEY_Break */ \
   OP(XKB_KEY_Caps_Lock, Key_CapsLock) /* XKB_KEY_Caps_Lock, Caps lock  */ \
   OP(XKB_KEY_Control_L, Key_LeftControl) /* XKB_KEY_Control_L, Left control  */ \
   OP(XKB_KEY_Control_R, Key_RightControl) /* XKB_KEY_Control_R, Right control  */ \
   OP(XKB_KEY_Delete, Key_Delete) /* XKB_KEY_Delete, Delete, rubout  */ \
   OP(XKB_KEY_Down, Key_DownArrow) /* XKB_KEY_Down, Move down, down arrow  */ \
   OP(XKB_KEY_End, Key_End) /* XKB_KEY_End, EOL  */ \
   OP(XKB_KEY_Escape, Key_Escape) /* XKB_KEY_Escape */ \
   OP(XKB_KEY_F1, Key_F1) /* XKB_KEY_F1 */ \
   OP(XKB_KEY_F10, Key_F10) /* XKB_KEY_F10 */ \
   OP(XKB_KEY_F11, Key_F11) /* XKB_KEY_F11 */ \
   OP(XKB_KEY_F12, Key_F12) /* XKB_KEY_F12 */ \
   OP(XKB_KEY_F2, Key_F2) /* XKB_KEY_F2 */ \
   OP(XKB_KEY_F3, Key_F3) /* XKB_KEY_F3 */ \
   OP(XKB_KEY_F4, Key_F4) /* XKB_KEY_F4 */ \
   OP(XKB_KEY_F5, Key_F5) /* XKB_KEY_F5 */ \
   OP(XKB_KEY_F6, Key_F6) /* XKB_KEY_F6 */ \
   OP(XKB_KEY_F7, Key_F7) /* XKB_KEY_F7 */ \
   OP(XKB_KEY_F8, Key_F8) /* XKB_KEY_F8 */ \
   OP(XKB_KEY_F9, Key_F9) /* XKB_KEY_F9 */ \
   OP(XKB_KEY_Home, Key_Home) /* XKB_KEY_Home */ \
   OP(XKB_KEY_ISO_Left_Tab, LSHIFT(Key_Tab)) /* XKB_KEY_ISO_Left_Tab */ \
   OP(XKB_KEY_Insert, Key_Insert) /* XKB_KEY_Insert, Insert, insert here  */ \
   OP(XKB_KEY_KP_0, LSHIFT(Key_Keypad0)) /* XKB_KEY_KP_0 */ \
   OP(XKB_KEY_KP_1, LSHIFT(Key_Keypad1)) /* XKB_KEY_KP_1 */ \
   OP(XKB_KEY_KP_2, LSHIFT(Key_Keypad2)) /* XKB_KEY_KP_2 */ \
   OP(XKB_KEY_KP_3, LSHIFT(Key_Keypad3)) /* XKB_KEY_KP_3 */ \
   OP(XKB_KEY_KP_4, LSHIFT(Key_Keypad4)) /* XKB_KEY_KP_4 */ \
   OP(XKB_KEY_KP_5, LSHIFT(Key_Keypad5)) /* XKB_KEY_KP_5 */ \
   OP(XKB_KEY_KP_6, LSHIFT(Key_Keypad6)) /* XKB_KEY_KP_6 */ \
   OP(XKB_KEY_KP_7, LSHIFT(Key_Keypad7)) /* XKB_KEY_KP_7 */ \
   OP(XKB_KEY_KP_8, LSHIFT(Key_Keypad8)) /* XKB_KEY_KP_8 */ \
   OP(XKB_KEY_KP_9, LSHIFT(Key_Keypad9)) /* XKB_KEY_KP_9 */ \
   OP(XKB_KEY_KP_Add, Key_KeypadAdd) /* XKB_KEY_KP_Add */ \
   OP(XKB_KEY_KP_Begin, Key_Keypad5) /* XKB_KEY_KP_Begin */ \
   OP(XKB_KEY_KP_Decimal, LSHIFT(Key_KeypadDot)) /* XKB_KEY_KP_Decimal */ \
   OP(XKB_KEY_KP_Delete, Key_KeypadDot) /* XKB_KEY_KP_Delete */ \
   OP(XKB_KEY_KP_Divide, Key_KeypadDivide) /* XKB_KEY_KP_Divide */ \
   OP(XKB_KEY_KP_Down, Key_Keypad2) /* XKB_KEY_KP_Down */ \
   OP(XKB_KEY_KP_End, Key_Keypad1) /* XKB_KEY_KP_End */ \
   OP(XKB_KEY_KP_Enter, Key_KeypadEnter) /* XKB_KEY_KP_Enter, Enter  */ \
   OP(XKB_KEY_KP_Home, Key_Keypad7) /* XKB_KEY_KP_Home */ \
   OP(XKB_KEY_KP_Insert, Key_Keypad0) /* XKB_KEY_KP_Insert */ \
   OP(XKB_KEY_KP_Left, Key_Keypad4) /* XKB_KEY_KP_Left */ \
   OP(XKB_KEY_KP_Multiply, Key_KeypadMultiply) /* XKB_KEY_KP_Multiply */ \
   OP(XKB_KEY_KP_Next, Key_Keypad3) /* XKB_KEY_KP_Next */ \
   OP(XKB_KEY_KP_Prior, Key_Keypad9) /* XKB_KEY_KP_Prior */ \
   OP(XKB_KEY_KP_Right, Key_Keypad6) /* XKB_KEY_KP_Right */ \
   OP(XKB_KEY_KP_Subtract, Key_KeypadSubtract) /* XKB_KEY_KP_Subtract */ \
   OP(XKB_KEY_KP_Up, Key_Keypad8) /* XKB_KEY_KP_Up */ \
   OP(XKB_KEY_Left, Key_LeftArrow) /* XKB_KEY_Left, Move left, left arrow  */ \
   OP(XKB_KEY_Menu, Key_PcApplication) /* XKB_KEY_Menu */ \
   OP(XKB_KEY_Meta_L, LSHIFT(Key_LeftAlt)) /* XKB_KEY_Meta_L, Left meta  */ \
   OP(XKB_KEY_Meta_R, LSHIFT(Key_RightAlt)) /* XKB_KEY_Meta_R, Right meta  */ \
   OP(XKB_KEY_Next, Key_PageDown) /* XKB_KEY_Next, Next  */ \
   OP(XKB_KEY_Num_Lock, Key_KeypadNumLock) /* XKB_KEY_Num_Lock */ \
   OP(XKB_KEY_Pause, Key_Pause) /* XKB_KEY_Pause, Pause, hold  */ \
   OP(XKB_KEY_Print, Key_PrintScreen) /* XKB_KEY_Print */ \
   OP(XKB_KEY_Prior, Key_PageUp) /* XKB_KEY_Prior, Prior, previous  */ \
   OP(XKB_KEY_Return, Key_Enter) /* XKB_KEY_Return, Return, enter  */ \
   OP(XKB_KEY_Right, Key_RightArrow) /* XKB_KEY_Right, Move right, right arrow  */ \
   OP(XKB_KEY_Scroll_Lock, Key_ScrollLock) /* XKB_KEY_Scroll_Lock */ \
   OP(XKB_KEY_Shift_L, Key_LeftShift) /* XKB_KEY_Shift_L, Left shift  */ \
   OP(XKB_KEY_Shift_R, Key_RightShift) /* XKB_KEY_Shift_R, Right shift  */ \
   OP(XKB_KEY_Super_L, Key_LeftGui) /* XKB_KEY_Super_L, Left super  */ \
   OP(XKB_KEY_Super_R, Key_RightGui) /* XKB_KEY_Super_R, Right super  */ \
   OP(XKB_KEY_Sys_Req, LALT(Key_PrintScreen)) /* XKB_KEY_Sys_Req */ \
   OP(XKB_KEY_Tab, Key_Tab) /* XKB_KEY_Tab */ \
   OP(XKB_KEY_Thai_baht, LSHIFT(Key_7)) \
   OP(XKB_KEY_Thai_bobaimai, Key_LeftBracket) \
   OP(XKB_KEY_Thai_chochan, Key_0) \
   OP(XKB_KEY_Thai_chochang, Key_Equals) \
   OP(XKB_KEY_Thai_choching, LSHIFT(Key_C)) \
   OP(XKB_KEY_Thai_chochoe, LSHIFT(Key_G)) \
   OP(XKB_KEY_Thai_dochada, LSHIFT(Key_E)) \
   OP(XKB_KEY_Thai_dodek, Key_F) \
   OP(XKB_KEY_Thai_fofa, Key_Slash) \
   OP(XKB_KEY_Thai_fofan, Key_A) \
   OP(XKB_KEY_Thai_hohip, Key_S) \
   OP(XKB_KEY_Thai_honokhuk, LSHIFT(Key_V)) \
   OP(XKB_KEY_Thai_khokhai, Key_Minus) \
   OP(XKB_KEY_Thai_khokhon, LSHIFT(Key_NonUsPound)) \
   OP(XKB_KEY_Thai_khokhuat, Key_NonUsPound) \
   OP(XKB_KEY_Thai_khokhwai, Key_8) \
   OP(XKB_KEY_Thai_khorakhang, LSHIFT(Key_S)) \
   OP(XKB_KEY_Thai_kokai, Key_D) \
   OP(XKB_KEY_Thai_lakkhangyao, Key_1) \
   OP(XKB_KEY_Thai_lekchet, LSHIFT(Key_0)) \
   OP(XKB_KEY_Thai_lekha, LSHIFT(Key_8)) \
   OP(XKB_KEY_Thai_lekhok, LSHIFT(Key_9)) \
   OP(XKB_KEY_Thai_lekkao, LSHIFT(Key_Equals)) \
   OP(XKB_KEY_Thai_leknung, LSHIFT(Key_2)) \
   OP(XKB_KEY_Thai_lekpaet, LSHIFT(Key_Minus)) \
   OP(XKB_KEY_Thai_leksam, LSHIFT(Key_4)) \
   OP(XKB_KEY_Thai_leksi, LSHIFT(Key_5)) \
   OP(XKB_KEY_Thai_leksong, LSHIFT(Key_3)) \
   OP(XKB_KEY_Thai_leksun, LSHIFT(Key_Q)) \
   OP(XKB_KEY_Thai_lochula, LSHIFT(Key_Period)) \
   OP(XKB_KEY_Thai_loling, Key_RightBracket) \
   OP(XKB_KEY_Thai_lu, LSHIFT(Key_Slash)) \
   OP(XKB_KEY_Thai_maichattawa, LSHIFT(Key_J)) \
   OP(XKB_KEY_Thai_maiek, Key_J) \
   OP(XKB_KEY_Thai_maihanakat, Key_Y) \
   OP(XKB_KEY_Thai_maitaikhu, LSHIFT(Key_H)) \
   OP(XKB_KEY_Thai_maitho, Key_H) \
   OP(XKB_KEY_Thai_maitri, LSHIFT(Key_U)) \
   OP(XKB_KEY_Thai_maiyamok, Key_Q) \
   OP(XKB_KEY_Thai_moma, Key_Comma) \
   OP(XKB_KEY_Thai_ngongu, Key_Quote) \
   OP(XKB_KEY_Thai_nikhahit, LSHIFT(Key_Y)) \
   OP(XKB_KEY_Thai_nonen, LSHIFT(Key_I)) \
   OP(XKB_KEY_Thai_nonu, Key_O) \
   OP(XKB_KEY_Thai_oang, Key_V) \
   OP(XKB_KEY_Thai_paiyannoi, LSHIFT(Key_O)) \
   OP(XKB_KEY_Thai_phinthu, LSHIFT(Key_B)) \
   OP(XKB_KEY_Thai_phophan, Key_R) \
   OP(XKB_KEY_Thai_phophung, Key_Z) \
   OP(XKB_KEY_Thai_phosamphao, Key_4) \
   OP(XKB_KEY_Thai_popla, Key_X) \
   OP(XKB_KEY_Thai_rorua, Key_I) \
   OP(XKB_KEY_Thai_ru, LSHIFT(Key_A)) \
   OP(XKB_KEY_Thai_saraa, Key_T) \
   OP(XKB_KEY_Thai_saraaa, Key_K) \
   OP(XKB_KEY_Thai_saraae, Key_C) \
   OP(XKB_KEY_Thai_saraaimaimalai, Key_W) \
   OP(XKB_KEY_Thai_saraaimaimuan, Key_Period) \
   OP(XKB_KEY_Thai_saraam, Key_E) \
   OP(XKB_KEY_Thai_sarae, Key_G) \
   OP(XKB_KEY_Thai_sarai, Key_B) \
   OP(XKB_KEY_Thai_saraii, Key_U) \
   OP(XKB_KEY_Thai_sarao, LSHIFT(Key_F)) \
   OP(XKB_KEY_Thai_sarau, Key_6) \
   OP(XKB_KEY_Thai_saraue, Key_7) \
   OP(XKB_KEY_Thai_sarauee, Key_N) \
   OP(XKB_KEY_Thai_sarauu, LSHIFT(Key_6)) \
   OP(XKB_KEY_Thai_sorusi, LSHIFT(Key_K)) \
   OP(XKB_KEY_Thai_sosala, LSHIFT(Key_L)) \
   OP(XKB_KEY_Thai_soso, LSHIFT(Key_Semicolon)) \
   OP(XKB_KEY_Thai_sosua, Key_L) \
   OP(XKB_KEY_Thai_thanthakhat, LSHIFT(Key_N)) \
   OP(XKB_KEY_Thai_thonangmontho, LSHIFT(Key_R)) \
   OP(XKB_KEY_Thai_thophuthao, LSHIFT(Key_Comma)) \
   OP(XKB_KEY_Thai_thothahan, Key_M) \
   OP(XKB_KEY_Thai_thothan, LSHIFT(Key_LeftBracket)) \
   OP(XKB_KEY_Thai_thothong, LSHIFT(Key_T)) \
   OP(XKB_KEY_Thai_thothung, Key_5) \
   OP(XKB_KEY_Thai_topatak, LSHIFT(Key_D)) \
   OP(XKB_KEY_Thai_totao, Key_9) \
   OP(XKB_KEY_Thai_wowaen, Key_Semicolon) \
   OP(XKB_KEY_Thai_yoyak, Key_P) \
   OP(XKB_KEY_Thai_yoying, LSHIFT(Key_P)) \
   OP(XKB_KEY_Up, Key_UpArrow) /* XKB_KEY_Up, Move up, up arrow  */ \
   OP(XKB_KEY_XF86ClearGrab, LCTRL(LALT(Key_KeypadMultiply))) /* XKB_KEY_XF86ClearGrab, kill application with grab  */ \
   OP(XKB_KEY_XF86Next_VMode, LCTRL(LALT(Key_KeypadAdd))) /* XKB_KEY_XF86Next_VMode, next video mode available   */ \
   OP(XKB_KEY_XF86Prev_VMode, LCTRL(LALT(Key_KeypadSubtract))) /* XKB_KEY_XF86Prev_VMode, prev. video mode available  */ \
   OP(XKB_KEY_XF86Switch_VT_1, LCTRL(LALT(Key_F1))) /* XKB_KEY_XF86Switch_VT_1 */ \
   OP(XKB_KEY_XF86Switch_VT_10, LCTRL(LALT(Key_F10))) /* XKB_KEY_XF86Switch_VT_10 */ \
   OP(XKB_KEY_XF86Switch_VT_11, LCTRL(LALT(Key_F11))) /* XKB_KEY_XF86Switch_VT_11 */ \
   OP(XKB_KEY_XF86Switch_VT_12, LCTRL(LALT(Key_F12))) /* XKB_KEY_XF86Switch_VT_12 */ \
   OP(XKB_KEY_XF86Switch_VT_2, LCTRL(LALT(Key_F2))) /* XKB_KEY_XF86Switch_VT_2 */ \
   OP(XKB_KEY_XF86Switch_VT_3, LCTRL(LALT(Key_F3))) /* XKB_KEY_XF86Switch_VT_3 */ \
   OP(XKB_KEY_XF86Switch_VT_4, LCTRL(LALT(Key_F4))) /* XKB_KEY_XF86Switch_VT_4 */ \
   OP(XKB_KEY_XF86Switch_VT_5, LCTRL(LALT(Key_F5))) /* XKB_KEY_XF86Switch_VT_5 */ \
   OP(XKB_KEY_XF86Switch_VT_6, LCTRL(LALT(Key_F6))) /* XKB_KEY_XF86Switch_VT_6 */ \
   OP(XKB_KEY_XF86Switch_VT_7, LCTRL(LALT(Key_F7))) /* XKB_KEY_XF86Switch_VT_7 */ \
   OP(XKB_KEY_XF86Switch_VT_8, LCTRL(LALT(Key_F8))) /* XKB_KEY_XF86Switch_VT_8 */ \
   OP(XKB_KEY_XF86Switch_VT_9, LCTRL(LALT(Key_F9))) /* XKB_KEY_XF86Switch_VT_9 */ \
   OP(XKB_KEY_XF86Ungrab, LCTRL(LALT(Key_KeypadDivide))) /* XKB_KEY_XF86Ungrab, force ungrab                */ \
   OP(XKB_KEY_comma, LSHIFT(Key_RightBracket)) \
   OP(XKB_KEY_greater, LSHIFT(Key_NonUsBackslashAndPipe)) \
   OP(XKB_KEY_less, Key_NonUsBackslashAndPipe) \
   OP(XKB_KEY_minus, Key_3) \
   OP(XKB_KEY_parenleft, LSHIFT(Key_Z)) \
   OP(XKB_KEY_parenright, LSHIFT(Key_X)) \
   OP(XKB_KEY_percent, LSHIFT(Key_Backtick)) \
   OP(XKB_KEY_period, LSHIFT(Key_Quote)) \
   OP(XKB_KEY_plus, LSHIFT(Key_1)) \
   OP(XKB_KEY_question, LSHIFT(Key_M)) \
   OP(XKB_KEY_quotedbl, LSHIFT(Key_W)) \
   OP(XKB_KEY_slash, Key_2) \
   OP(XKB_KEY_space, Key_Spacebar) \
   OP(XKB_KEY_underscore, Key_Backtick) \


namespace kaleidoscope {
namespace host_keymap {
namespace linux {
namespace th {
namespace standard {

HOST_KEYMAP_LINUX(
  _HOST_KEYMAP_ASCII,
  _HOST_KEYMAP_UNICODE,
  _HOST_KEYMAP_NON_PRINTABLE
)

} // namespace standard
} // namespace th
} // namespace linux
} // namespace host_keymap
} // namespace kaleidoscope

#undef _HOST_KEYMAP_ASCII
#undef _HOST_KEYMAP_UNICODE
#undef _HOST_KEYMAP_NON_PRINTABLE

