#pragma once


#define Consumer_NumericKeyPad (Key) { HID_CONSUMER_NUMERIC_KEY_PAD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_ProgrammableButtons (Key) { HID_CONSUMER_PROGRAMMABLE_BUTTONS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_MicrophoneCa (Key) { HID_CONSUMER_MICROPHONE_CA, KEY_FLAGS | SYNTHETIC|IS_CONSUMER }
#define Consumer_HeadphoneCa (Key) { HID_CONSUMER_HEADPHONE_CA, KEY_FLAGS | SYNTHETIC|IS_CONSUMER }
#define Consumer_GraphicEqualizerCa (Key) { HID_CONSUMER_GRAPHIC_EQUALIZER_CA, KEY_FLAGS | SYNTHETIC|IS_CONSUMER }

#define Consumer_Plus10 (Key) { HID_CONSUMER_PLUS_10, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Plus100 (Key) { HID_CONSUMER_PLUS_100, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_AMSlashPM (Key) { HID_CONSUMER_AM_SLASH_PM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }

#define Consumer_Power (Key) { HID_CONSUMER_POWER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Reset (Key) { HID_CONSUMER_RESET, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Sleep (Key) { HID_CONSUMER_SLEEP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Sleep_After (Key) { HID_CONSUMER_SLEEP_AFTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Sleep_Mode (Key) { HID_CONSUMER_SLEEP_MODE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }
#define Consumer_Illumination (Key) { HID_CONSUMER_ILLUMINATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Function_Buttons (Key) { HID_CONSUMER_FUNCTION_BUTTONS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }

#define Consumer_Menu (Key) { HID_CONSUMER_MENU, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_MenuPick (Key) { HID_CONSUMER_MENU_PICK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuUp (Key) { HID_CONSUMER_MENU_UP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuDown (Key) { HID_CONSUMER_MENU_DOWN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuLeft (Key) { HID_CONSUMER_MENU_LEFT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuRight (Key) { HID_CONSUMER_MENU_RIGHT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuEscape (Key) { HID_CONSUMER_MENU_ESCAPE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuValueIncrease (Key) { HID_CONSUMER_MENU_VALUE_INCREASE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MenuValueDecrease (Key) { HID_CONSUMER_MENU_VALUE_DECREASE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }

#define Consumer_DataOnScreen (Key) { HID_CONSUMER_DATA_ON_SCREEN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_ClosedCaption (Key) { HID_CONSUMER_CLOSED_CAPTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_ClosedCaptionSelect (Key) { HID_CONSUMER_CLOSED_CAPTION_SELECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_VCRSlashTV (Key) { HID_CONSUMER_VCR_SLASH_TV, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_BroadcastMode (Key) { HID_CONSUMER_BROADCAST_MODE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_SNapshot (Key) { HID_CONSUMER_SNAPSHOT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Still (Key) { HID_CONSUMER_STILL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }

#define Consumer_Selection (Key) { HID_CONSUMER_SELECTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_AssignSelection (Key) { HID_CONSUMER_ASSIGN_SELECTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_ModeStep (Key) { HID_CONSUMER_MODE_STEP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_RecallLast (Key) { HID_CONSUMER_RECALL_LAST, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_EnterChannel (Key) { HID_CONSUMER_ENTER_CHANNEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_OrderMovie (Key) { HID_CONSUMER_ORDER_MOVIE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Channel (Key) { HID_CONSUMER_CHANNEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_MediaSelection (Key) { HID_CONSUMER_MEDIA_SELECTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_MediaSelectComputer (Key) { HID_CONSUMER_MEDIA_SELECT_COMPUTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectTV (Key) { HID_CONSUMER_MEDIA_SELECT_TV, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectWww (Key) { HID_CONSUMER_MEDIA_SELECT_WWW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectDvd (Key) { HID_CONSUMER_MEDIA_SELECT_DVD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectTelephone (Key) { HID_CONSUMER_MEDIA_SELECT_TELEPHONE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectProgramGuide (Key) { HID_CONSUMER_MEDIA_SELECT_PROGRAM_GUIDE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectVideoPhone (Key) { HID_CONSUMER_MEDIA_SELECT_VIDEO_PHONE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectGames (Key) { HID_CONSUMER_MEDIA_SELECT_GAMES, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectMessages (Key) { HID_CONSUMER_MEDIA_SELECT_MESSAGES, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectCd (Key) { HID_CONSUMER_MEDIA_SELECT_CD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectVcr (Key) { HID_CONSUMER_MEDIA_SELECT_VCR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectTuner (Key) { HID_CONSUMER_MEDIA_SELECT_TUNER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_Quit (Key) { HID_CONSUMER_QUIT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Help (Key) { HID_CONSUMER_HELP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_MediaSelectTape (Key) { HID_CONSUMER_MEDIA_SELECT_TAPE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectCable (Key) { HID_CONSUMER_MEDIA_SELECT_CABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectSatellite (Key) { HID_CONSUMER_MEDIA_SELECT_SATELLITE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectSecurity (Key) { HID_CONSUMER_MEDIA_SELECT_SECURITY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectHome (Key) { HID_CONSUMER_MEDIA_SELECT_HOME, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_MediaSelectCall (Key) { HID_CONSUMER_MEDIA_SELECT_CALL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_ChannelIncrement (Key) { HID_CONSUMER_CHANNEL_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_ChannelDecrement (Key) { HID_CONSUMER_CHANNEL_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_MediaSelectSap (Key) { HID_CONSUMER_MEDIA_SELECT_SAP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }

#define Consumer_VcrPlus (Key) { HID_CONSUMER_VCR_PLUS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Once (Key) { HID_CONSUMER_ONCE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Daily (Key) { HID_CONSUMER_DAILY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Weekly (Key) { HID_CONSUMER_WEEKLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Monthly (Key) { HID_CONSUMER_MONTHLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }

#define Consumer_Play (Key) { HID_CONSUMER_PLAY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Pause (Key) { HID_CONSUMER_PAUSE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Record (Key) { HID_CONSUMER_RECORD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_FastForward (Key) { HID_CONSUMER_FAST_FORWARD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Rewind (Key) { HID_CONSUMER_REWIND, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_ScanNextTrack (Key) { HID_CONSUMER_SCAN_NEXT_TRACK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_ScanPreviousTrack (Key) { HID_CONSUMER_SCAN_PREVIOUS_TRACK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Stop (Key) { HID_CONSUMER_STOP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Eject (Key) { HID_CONSUMER_EJECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_RandomPlay (Key) { HID_CONSUMER_RANDOM_PLAY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_SelectDisc (Key) { HID_CONSUMER_SELECT_DISC, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_EnterDiscMc (Key) { HID_CONSUMER_ENTER_DISC_MC, KEY_FLAGS | SYNTHETIC|IS_CONSUMER }
#define Consumer_Repeat (Key) { HID_CONSUMER_REPEAT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Tracking (Key) { HID_CONSUMER_TRACKING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_Track_Normal (Key) { HID_CONSUMER_TRACK_NORMAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_SlowTracking (Key) { HID_CONSUMER_SLOW_TRACKING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_FrameForward (Key) { HID_CONSUMER_FRAME_FORWARD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }
#define Consumer_FrameBack (Key) { HID_CONSUMER_FRAME_BACK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }
#define Consumer_Mark (Key) { HID_CONSUMER_MARK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_ClearMark (Key) { HID_CONSUMER_CLEAR_MARK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_RepeatFromMark (Key) { HID_CONSUMER_REPEAT_FROM_MARK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_ReturnTo_Mark (Key) { HID_CONSUMER_RETURN_TO_MARK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_SearchMarkForward (Key) { HID_CONSUMER_SEARCH_MARK_FORWARD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_SearchMarkBackwards (Key) { HID_CONSUMER_SEARCH_MARK_BACKWARDS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_CounterReset (Key) { HID_CONSUMER_COUNTER_RESET, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_ShowCounter (Key) { HID_CONSUMER_SHOW_COUNTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_TrackingIncrement (Key) { HID_CONSUMER_TRACKING_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }
#define Consumer_TrackingDecrement (Key) { HID_CONSUMER_TRACKING_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }
#define Consumer_StopSlashEject (Key) { HID_CONSUMER_STOP_SLASH_EJECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_PlaySlashPause (Key) { HID_CONSUMER_PLAY_SLASH_PAUSE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_PlaySlashSkip (Key) { HID_CONSUMER_PLAY_SLASH_SKIP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Volume (Key) { HID_CONSUMER_VOLUME, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_Balance (Key) { HID_CONSUMER_BALANCE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_Mute (Key) { HID_CONSUMER_MUTE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Bass (Key) { HID_CONSUMER_BASS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_Treble (Key) { HID_CONSUMER_TREBLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC }
#define Consumer_BassBoost (Key) { HID_CONSUMER_BASS_BOOST, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_SurroundMode (Key) { HID_CONSUMER_SURROUND_MODE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_Loudness (Key) { HID_CONSUMER_LOUDNESS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_Mpx (Key) { HID_CONSUMER_MPX, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC }
#define Consumer_VolumeIncrement (Key) { HID_CONSUMER_VOLUME_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }


#define Consumer_VolumeDecrement (Key) { HID_CONSUMER_VOLUME_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC }

#define Consumer_SpeedSelect (Key) { HID_CONSUMER_SPEED_SELECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }
#define Consumer_PlaybackSpeed (Key) { HID_CONSUMER_PLAYBACK_SPEED, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY }
#define Consumer_StandardPlay (Key) { HID_CONSUMER_STANDARD_PLAY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_LongPlay (Key) { HID_CONSUMER_LONG_PLAY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_ExtendedPlay (Key) { HID_CONSUMER_EXTENDED_PLAY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL }
#define Consumer_Slow (Key) { HID_CONSUMER_SLOW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC }

#define Consumer_FanEnable (Key) Key_16bit(HID_CONSUMER_FAN_ENABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC)
#define Consumer_FanSpeed (Key) Key_16bit(HID_CONSUMER_FAN_SPEED, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_LightEnable (Key) Key_16bit(HID_CONSUMER_LIGHT_ENABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC)
#define Consumer_LightIlluminationLevel (Key) Key_16bit(HID_CONSUMER_LIGHT_ILLUMINATION_LEVEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_ClimateControlEnable (Key) Key_16bit(HID_CONSUMER_CLIMATE_CONTROL_ENABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC)
#define Consumer_RoomTemperature (Key) Key_16bit(HID_CONSUMER_ROOM_TEMPERATURE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_SecurityEnable (Key) Key_16bit(HID_CONSUMER_SECURITY_ENABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OOC)
#define Consumer_FireAlarm (Key) Key_16bit(HID_CONSUMER_FIRE_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_PoliceAlarm (Key) Key_16bit(HID_CONSUMER_POLICE_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_Proximity (Key) Key_16bit(HID_CONSUMER_PROXIMITY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_Motion (Key) Key_16bit(HID_CONSUMER_MOTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_DuressAlarm (Key) Key_16bit(HID_CONSUMER_DURESS_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_HoldupAlarm (Key) Key_16bit(HID_CONSUMER_HOLDUP_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_MedicalAlarm (Key) Key_16bit(HID_CONSUMER_MEDICAL_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)

#define Consumer_BalanceRight (Key) Key_16bit(HID_CONSUMER_BALANCE_RIGHT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)
#define Consumer_BalanceLeft (Key) Key_16bit(HID_CONSUMER_BALANCE_LEFT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)
#define Consumer_BassIncrement (Key) Key_16bit(HID_CONSUMER_BASS_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)
#define Consumer_BassDecrement (Key) Key_16bit(HID_CONSUMER_BASS_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)
#define Consumer_TrebleIncrement (Key) Key_16bit(HID_CONSUMER_TREBLE_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)
#define Consumer_TrebleDecrement (Key) Key_16bit(HID_CONSUMER_TREBLE_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_RTC)

#define Consumer_SpeakerSystem (Key) Key_16bit(HID_CONSUMER_SPEAKER_SYSTEM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelLeft (Key) Key_16bit(HID_CONSUMER_CHANNEL_LEFT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelRight (Key) Key_16bit(HID_CONSUMER_CHANNEL_RIGHT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelCenter (Key) Key_16bit(HID_CONSUMER_CHANNEL_CENTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelFront (Key) Key_16bit(HID_CONSUMER_CHANNEL_FRONT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelCenterFront (Key) Key_16bit(HID_CONSUMER_CHANNEL_CENTER_FRONT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelSide (Key) Key_16bit(HID_CONSUMER_CHANNEL_SIDE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelSurround (Key) Key_16bit(HID_CONSUMER_CHANNEL_SURROUND, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelLowFrequencyEnhancement (Key) Key_16bit(HID_CONSUMER_CHANNEL_LOW_FREQUENCY_ENHANCEMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelTop (Key) Key_16bit(HID_CONSUMER_CHANNEL_TOP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)
#define Consumer_ChannelUnknown (Key) Key_16bit(HID_CONSUMER_CHANNEL_UNKNOWN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_CL)

#define Consumer_SubChannel (Key) Key_16bit(HID_CONSUMER_SUB_CHANNEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_SubChannelIncrement (Key) Key_16bit(HID_CONSUMER_SUB_CHANNEL_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_SubChannelDecrement (Key) Key_16bit(HID_CONSUMER_SUB_CHANNEL_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_AlternateAudioIncrement (Key) Key_16bit(HID_CONSUMER_ALTERNATE_AUDIO_INCREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)
#define Consumer_AlternateAudioDecrement (Key) Key_16bit(HID_CONSUMER_ALTERNATE_AUDIO_DECREMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_OSC)

#define Consumer_Application_Launch_Buttons (Key) Key_16bit(HID_CONSUMER_APPLICATION_LAUNCH_BUTTONS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_NARY)
#define Consumer_AL_Launch_Button_Configuration_Tool (Key) Key_16bit(HID_CONSUMER_AL_LAUNCH_BUTTON_CONFIGURATION_TOOL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Programmable_Button_Configuration (Key) Key_16bit(HID_CONSUMER_AL_PROGRAMMABLE_BUTTON_CONFIGURATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Consumer_Control_Configuration (Key) Key_16bit(HID_CONSUMER_AL_CONSUMER_CONTROL_CONFIGURATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Word_Processor (Key) Key_16bit(HID_CONSUMER_AL_WORD_PROCESSOR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Text_Editor (Key) Key_16bit(HID_CONSUMER_AL_TEXT_EDITOR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Spreadsheet (Key) Key_16bit(HID_CONSUMER_AL_SPREADSHEET, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Graphics_Editor (Key) Key_16bit(HID_CONSUMER_AL_GRAPHICS_EDITOR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Presentation_App (Key) Key_16bit(HID_CONSUMER_AL_PRESENTATION_APP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Database_App (Key) Key_16bit(HID_CONSUMER_AL_DATABASE_APP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Email_Reader (Key) Key_16bit(HID_CONSUMER_AL_EMAIL_READER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Newsreader (Key) Key_16bit(HID_CONSUMER_AL_NEWSREADER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Voicemail (Key) Key_16bit(HID_CONSUMER_AL_VOICEMAIL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Contacts_Slash_Address_Book (Key) Key_16bit(HID_CONSUMER_AL_CONTACTS_SLASH_ADDRESS_BOOK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Calendar_Slash_Schedule (Key) Key_16bit(HID_CONSUMER_AL_CALENDAR_SLASH_SCHEDULE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Task_Slash_Project_Manager (Key) Key_16bit(HID_CONSUMER_AL_TASK_SLASH_PROJECT_MANAGER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Log_Slash_Journal_Slash_Timecard (Key) Key_16bit(HID_CONSUMER_AL_LOG_SLASH_JOURNAL_SLASH_TIMECARD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Checkbook_Slash_Finance (Key) Key_16bit(HID_CONSUMER_AL_CHECKBOOK_SLASH_FINANCE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Calculator (Key) Key_16bit(HID_CONSUMER_AL_CALCULATOR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_AVCaptureSlashPlayback (Key) Key_16bit(HID_CONSUMER_AL_A_SLASH_V_CAPTURE_SLASH_PLAYBACK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Local_MachineBrowser (Key) Key_16bit(HID_CONSUMER_AL_LOCAL_MACHINE_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Lan_SlashWanBrowser (Key) Key_16bit(HID_CONSUMER_AL_LAN_SLASH_WAN_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_InternetBrowser (Key) Key_16bit(HID_CONSUMER_AL_INTERNET_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_RemoteNetworkingSlashIspConnect (Key) Key_16bit(HID_CONSUMER_AL_REMOTE_NETWORKING_SLASH_ISP_CONNECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_NetworkConference (Key) Key_16bit(HID_CONSUMER_AL_NETWORK_CONFERENCE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_NetworkChat (Key) Key_16bit(HID_CONSUMER_AL_NETWORK_CHAT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_TelephonySlashDialer (Key) Key_16bit(HID_CONSUMER_AL_TELEPHONY_SLASH_DIALER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Logon (Key) Key_16bit(HID_CONSUMER_AL_LOGON, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Logoff (Key) Key_16bit(HID_CONSUMER_AL_LOGOFF, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_LogonSlashLogoff (Key) Key_16bit(HID_CONSUMER_AL_LOGON_SLASH_LOGOFF, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_TerminalLockSlashScreensaver (Key) Key_16bit(HID_CONSUMER_AL_TERMINAL_LOCK_SLASH_SCREENSAVER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_ControlPanel (Key) Key_16bit(HID_CONSUMER_AL_CONTROL_PANEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_CommandLineProcessorSlashRun (Key) Key_16bit(HID_CONSUMER_AL_COMMAND_LINE_PROCESSOR_SLASH_RUN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_ProcessSlashTask_Manager (Key) Key_16bit(HID_CONSUMER_AL_PROCESS_SLASH_TASK_MANAGER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_SelectTaskSlashApplication (Key) Key_16bit(HID_CONSUMER_AL_SELECT_TASK_SLASH_APPLICATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_NextTaskSlashApplication (Key) Key_16bit(HID_CONSUMER_AL_NEXT_TASK_SLASH_APPLICATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_PreviousTaskSlashApplication (Key) Key_16bit(HID_CONSUMER_AL_PREVIOUS_TASK_SLASH_APPLICATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_PreemptiveHaltTaskSlashApplication (Key) Key_16bit(HID_CONSUMER_AL_PREEMPTIVE_HALT_TASK_SLASH_APPLICATION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_IntegratedHelpCenter (Key) Key_16bit(HID_CONSUMER_AL_INTEGRATED_HELP_CENTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Documents (Key) Key_16bit(HID_CONSUMER_AL_DOCUMENTS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Thesaurus (Key) Key_16bit(HID_CONSUMER_AL_THESAURUS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Dictionary (Key) Key_16bit(HID_CONSUMER_AL_DICTIONARY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Desktop (Key) Key_16bit(HID_CONSUMER_AL_DESKTOP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_SpellCheck (Key) Key_16bit(HID_CONSUMER_AL_SPELL_CHECK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_GrammarCheck (Key) Key_16bit(HID_CONSUMER_AL_GRAMMAR_CHECK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_WirelessStatus (Key) Key_16bit(HID_CONSUMER_AL_WIRELESS_STATUS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_KeyboardLayout (Key) Key_16bit(HID_CONSUMER_AL_KEYBOARD_LAYOUT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_VirusProtection (Key) Key_16bit(HID_CONSUMER_AL_VIRUS_PROTECTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Encryption (Key) Key_16bit(HID_CONSUMER_AL_ENCRYPTION, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_ScreenSaver (Key) Key_16bit(HID_CONSUMER_AL_SCREEN_SAVER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Alarms (Key) Key_16bit(HID_CONSUMER_AL_ALARMS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Clock (Key) Key_16bit(HID_CONSUMER_AL_CLOCK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_FileBrowser (Key) Key_16bit(HID_CONSUMER_AL_FILE_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_PowerStatus (Key) Key_16bit(HID_CONSUMER_AL_POWER_STATUS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_ImageBrowser (Key) Key_16bit(HID_CONSUMER_AL_IMAGE_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_AudioBrowser (Key) Key_16bit(HID_CONSUMER_AL_AUDIO_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_MovieBrowser (Key) Key_16bit(HID_CONSUMER_AL_MOVIE_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_DigitalRightsManager (Key) Key_16bit(HID_CONSUMER_AL_DIGITAL_RIGHTS_MANAGER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_DigitalWallet (Key) Key_16bit(HID_CONSUMER_AL_DIGITAL_WALLET, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)

#define Consumer_AL_InstantMessaging (Key) Key_16bit(HID_CONSUMER_AL_INSTANT_MESSAGING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_OemFeaturesSlashTipsSlashTUTORIALBrowser (Key) Key_16bit(HID_CONSUMER_AL_OEM_FEATURES_SLASH__TIPS_SLASH_TUTORIAL_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_OemHelp (Key) Key_16bit(HID_CONSUMER_AL_OEM_HELP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_OnlineCommunity (Key) Key_16bit(HID_CONSUMER_AL_ONLINE_COMMUNITY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_Entertainment_Content_Browser (Key) Key_16bit(HID_CONSUMER_AL_ENTERTAINMENT_CONTENT_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_OnlineShoppingBrowser (Key) Key_16bit(HID_CONSUMER_AL_ONLINE_SHOPPING_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_SmartcardInformationSlashHelp (Key) Key_16bit(HID_CONSUMER_AL_SMARTCARD_INFORMATION_SLASH_HELP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_MarketMonitorSlashFinanceBrowser (Key) Key_16bit(HID_CONSUMER_AL_MARKET_MONITOR_SLASH_FINANCE_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_CustomizedCorporateNewsBrowser (Key) Key_16bit(HID_CONSUMER_AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_OnlineActivityBrowser (Key) Key_16bit(HID_CONSUMER_AL_ONLINE_ACTIVITY_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_ResearchSlashSearchBrowser (Key) Key_16bit(HID_CONSUMER_AL_RESEARCH_SLASH_SEARCH_BROWSER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AL_AudioPlayer (Key) Key_16bit(HID_CONSUMER_AL_AUDIO_PLAYER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)

#define Consumer_GenericGuiApplicationControls (Key) Key_16bit(HID_CONSUMER_GENERIC_GUI_APPLICATION_CONTROLS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER | HID_TYPE_NARY)
#define Consumer_AC_New (Key) Key_16bit(HID_CONSUMER_AC_NEW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Open (Key) Key_16bit(HID_CONSUMER_AC_OPEN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Close (Key) Key_16bit(HID_CONSUMER_AC_CLOSE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Exit (Key) Key_16bit(HID_CONSUMER_AC_EXIT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Maximize (Key) Key_16bit(HID_CONSUMER_AC_MAXIMIZE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Minimize (Key) Key_16bit(HID_CONSUMER_AC_MINIMIZE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Save (Key) Key_16bit(HID_CONSUMER_AC_SAVE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Print (Key) Key_16bit(HID_CONSUMER_AC_PRINT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Properties (Key) Key_16bit(HID_CONSUMER_AC_PROPERTIES, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Undo (Key) Key_16bit(HID_CONSUMER_AC_UNDO, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Copy (Key) Key_16bit(HID_CONSUMER_AC_COPY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Cut (Key) Key_16bit(HID_CONSUMER_AC_CUT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Paste (Key) Key_16bit(HID_CONSUMER_AC_PASTE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectAll (Key) Key_16bit(HID_CONSUMER_AC_SELECT_ALL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Find (Key) Key_16bit(HID_CONSUMER_AC_FIND, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FindAndReplace (Key) Key_16bit(HID_CONSUMER_AC_FIND_AND_REPLACE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Search (Key) Key_16bit(HID_CONSUMER_AC_SEARCH, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_GoTo (Key) Key_16bit(HID_CONSUMER_AC_GO_TO, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Home (Key) Key_16bit(HID_CONSUMER_AC_HOME, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Back (Key) Key_16bit(HID_CONSUMER_AC_BACK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Forward (Key) Key_16bit(HID_CONSUMER_AC_FORWARD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Stop (Key) Key_16bit(HID_CONSUMER_AC_STOP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Refresh (Key) Key_16bit(HID_CONSUMER_AC_REFRESH, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_PreviousLink (Key) Key_16bit(HID_CONSUMER_AC_PREVIOUS_LINK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_NextLink (Key) Key_16bit(HID_CONSUMER_AC_NEXT_LINK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Bookmarks (Key) Key_16bit(HID_CONSUMER_AC_BOOKMARKS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_History (Key) Key_16bit(HID_CONSUMER_AC_HISTORY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Subscriptions (Key) Key_16bit(HID_CONSUMER_AC_SUBSCRIPTIONS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ZoomIn (Key) Key_16bit(HID_CONSUMER_AC_ZOOM_IN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ZoomOut (Key) Key_16bit(HID_CONSUMER_AC_ZOOM_OUT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Zoom (Key) Key_16bit(HID_CONSUMER_AC_ZOOM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_AC_FullSCreenView (Key) Key_16bit(HID_CONSUMER_AC_FULL_SCREEN_VIEW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_NormalView (Key) Key_16bit(HID_CONSUMER_AC_NORMAL_VIEW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ViewToggle (Key) Key_16bit(HID_CONSUMER_AC_VIEW_TOGGLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ScrollUp (Key) Key_16bit(HID_CONSUMER_AC_SCROLL_UP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ScrollDown (Key) Key_16bit(HID_CONSUMER_AC_SCROLL_DOWN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Scroll (Key) Key_16bit(HID_CONSUMER_AC_SCROLL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_AC_PanLeft (Key) Key_16bit(HID_CONSUMER_AC_PAN_LEFT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_PanRight (Key) Key_16bit(HID_CONSUMER_AC_PAN_RIGHT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Pan (Key) Key_16bit(HID_CONSUMER_AC_PAN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_LC)
#define Consumer_AC_NewWindow (Key) Key_16bit(HID_CONSUMER_AC_NEW_WINDOW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_TileHorizontally (Key) Key_16bit(HID_CONSUMER_AC_TILE_HORIZONTALLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_TileVertically (Key) Key_16bit(HID_CONSUMER_AC_TILE_VERTICALLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Format (Key) Key_16bit(HID_CONSUMER_AC_FORMAT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Edit (Key) Key_16bit(HID_CONSUMER_AC_EDIT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Bold (Key) Key_16bit(HID_CONSUMER_AC_BOLD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Italics (Key) Key_16bit(HID_CONSUMER_AC_ITALICS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Underline (Key) Key_16bit(HID_CONSUMER_AC_UNDERLINE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Strikethrough (Key) Key_16bit(HID_CONSUMER_AC_STRIKETHROUGH, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Subscript (Key) Key_16bit(HID_CONSUMER_AC_SUBSCRIPT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Superscript (Key) Key_16bit(HID_CONSUMER_AC_SUPERSCRIPT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_AllCaps (Key) Key_16bit(HID_CONSUMER_AC_ALL_CAPS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Rotate (Key) Key_16bit(HID_CONSUMER_AC_ROTATE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Resize (Key) Key_16bit(HID_CONSUMER_AC_RESIZE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FlipHorizontal (Key) Key_16bit(HID_CONSUMER_AC_FLIP_HORIZONTAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FlipVertical (Key) Key_16bit(HID_CONSUMER_AC_FLIP_VERTICAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_MirrorHorizontal (Key) Key_16bit(HID_CONSUMER_AC_MIRROR_HORIZONTAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_MirrorVertical (Key) Key_16bit(HID_CONSUMER_AC_MIRROR_VERTICAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FontSelect (Key) Key_16bit(HID_CONSUMER_AC_FONT_SELECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FontColor (Key) Key_16bit(HID_CONSUMER_AC_FONT_COLOR, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_FontSize (Key) Key_16bit(HID_CONSUMER_AC_FONT_SIZE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyLeft (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_LEFT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyCenterH (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_CENTER_H, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyRight (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_RIGHT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyBlockH (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_BLOCK_H, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyTop (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_TOP, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyCenterV (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_CENTER_V, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyBottom (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_BOTTOM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_JustifyBlockV (Key) Key_16bit(HID_CONSUMER_AC_JUSTIFY_BLOCK_V, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_IndentDecrease (Key) Key_16bit(HID_CONSUMER_AC_INDENT_DECREASE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_IndentIncrease (Key) Key_16bit(HID_CONSUMER_AC_INDENT_INCREASE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_NumberedList (Key) Key_16bit(HID_CONSUMER_AC_NUMBERED_LIST, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_RestartNumbering (Key) Key_16bit(HID_CONSUMER_AC_RESTART_NUMBERING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_BulletedList (Key) Key_16bit(HID_CONSUMER_AC_BULLETED_LIST, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Promote (Key) Key_16bit(HID_CONSUMER_AC_PROMOTE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Demote (Key) Key_16bit(HID_CONSUMER_AC_DEMOTE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Yes (Key) Key_16bit(HID_CONSUMER_AC_YES, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_No (Key) Key_16bit(HID_CONSUMER_AC_NO, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Cancel (Key) Key_16bit(HID_CONSUMER_AC_CANCEL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Catalog (Key) Key_16bit(HID_CONSUMER_AC_CATALOG, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_BuySlashCheckout (Key) Key_16bit(HID_CONSUMER_AC_BUY_SLASH_CHECKOUT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_AddToCart (Key) Key_16bit(HID_CONSUMER_AC_ADD_TO_CART, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Expand (Key) Key_16bit(HID_CONSUMER_AC_EXPAND, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ExpandAll (Key) Key_16bit(HID_CONSUMER_AC_EXPAND_ALL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Collapse (Key) Key_16bit(HID_CONSUMER_AC_COLLAPSE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_CollapseAll (Key) Key_16bit(HID_CONSUMER_AC_COLLAPSE_ALL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_PrintPreview (Key) Key_16bit(HID_CONSUMER_AC_PRINT_PREVIEW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_PasteSpecial (Key) Key_16bit(HID_CONSUMER_AC_PASTE_SPECIAL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertMode (Key) Key_16bit(HID_CONSUMER_AC_INSERT_MODE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Delete (Key) Key_16bit(HID_CONSUMER_AC_DELETE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Lock (Key) Key_16bit(HID_CONSUMER_AC_LOCK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Unlock (Key) Key_16bit(HID_CONSUMER_AC_UNLOCK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Protect (Key) Key_16bit(HID_CONSUMER_AC_PROTECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Unprotect (Key) Key_16bit(HID_CONSUMER_AC_UNPROTECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_AttachComment (Key) Key_16bit(HID_CONSUMER_AC_ATTACH_COMMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_DeleteComment (Key) Key_16bit(HID_CONSUMER_AC_DELETE_COMMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ViewComment (Key) Key_16bit(HID_CONSUMER_AC_VIEW_COMMENT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectWord (Key) Key_16bit(HID_CONSUMER_AC_SELECT_WORD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectSentence (Key) Key_16bit(HID_CONSUMER_AC_SELECT_SENTENCE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectParagraph (Key) Key_16bit(HID_CONSUMER_AC_SELECT_PARAGRAPH, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectColumn (Key) Key_16bit(HID_CONSUMER_AC_SELECT_COLUMN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectRow (Key) Key_16bit(HID_CONSUMER_AC_SELECT_ROW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectTable (Key) Key_16bit(HID_CONSUMER_AC_SELECT_TABLE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectObject (Key) Key_16bit(HID_CONSUMER_AC_SELECT_OBJECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_RedoSlashRepeat (Key) Key_16bit(HID_CONSUMER_AC_REDO_SLASH_REPEAT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Sort (Key) Key_16bit(HID_CONSUMER_AC_SORT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Sort_Ascending (Key) Key_16bit(HID_CONSUMER_AC_SORT_ASCENDING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Sort_Descending (Key) Key_16bit(HID_CONSUMER_AC_SORT_DESCENDING, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Filter (Key) Key_16bit(HID_CONSUMER_AC_FILTER, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SetClock (Key) Key_16bit(HID_CONSUMER_AC_SET_CLOCK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ViewClock (Key) Key_16bit(HID_CONSUMER_AC_VIEW_CLOCK, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SelectTimeZone (Key) Key_16bit(HID_CONSUMER_AC_SELECT_TIME_ZONE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_EditTimeZones (Key) Key_16bit(HID_CONSUMER_AC_EDIT_TIME_ZONES, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SetAlarm (Key) Key_16bit(HID_CONSUMER_AC_SET_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ClearAlarm (Key) Key_16bit(HID_CONSUMER_AC_CLEAR_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SnoozeAlarm (Key) Key_16bit(HID_CONSUMER_AC_SNOOZE_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ResetAlarm (Key) Key_16bit(HID_CONSUMER_AC_RESET_ALARM, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Synchronize (Key) Key_16bit(HID_CONSUMER_AC_SYNCHRONIZE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SendSlashReceive (Key) Key_16bit(HID_CONSUMER_AC_SEND_SLASH_RECEIVE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SendTo (Key) Key_16bit(HID_CONSUMER_AC_SEND_TO, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Reply (Key) Key_16bit(HID_CONSUMER_AC_REPLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ReplyAll (Key) Key_16bit(HID_CONSUMER_AC_REPLY_ALL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_ForwardMsg (Key) Key_16bit(HID_CONSUMER_AC_FORWARD_MSG, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Send (Key) Key_16bit(HID_CONSUMER_AC_SEND, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_AttachFile (Key) Key_16bit(HID_CONSUMER_AC_ATTACH_FILE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Upload (Key) Key_16bit(HID_CONSUMER_AC_UPLOAD, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Download (Key) Key_16bit(HID_CONSUMER_AC_DOWNLOAD_(SAVE_TARGET_AS), KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SetBorders (Key) Key_16bit(HID_CONSUMER_AC_SET_BORDERS, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertRow (Key) Key_16bit(HID_CONSUMER_AC_INSERT_ROW, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertColumn (Key) Key_16bit(HID_CONSUMER_AC_INSERT_COLUMN, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertFile (Key) Key_16bit(HID_CONSUMER_AC_INSERT_FILE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertPicture (Key) Key_16bit(HID_CONSUMER_AC_INSERT_PICTURE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertObject (Key) Key_16bit(HID_CONSUMER_AC_INSERT_OBJECT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_InsertSymbol (Key) Key_16bit(HID_CONSUMER_AC_INSERT_SYMBOL, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_SaveandClose (Key) Key_16bit(HID_CONSUMER_AC_SAVE_AND_CLOSE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Rename (Key) Key_16bit(HID_CONSUMER_AC_RENAME, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Merge (Key) Key_16bit(HID_CONSUMER_AC_MERGE, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Split (Key) Key_16bit(HID_CONSUMER_AC_SPLIT, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Distribute_Horizontally (Key) Key_16bit(HID_CONSUMER_AC_DISTRIBUTE_HORIZONTALLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
#define Consumer_AC_Distribute_Vertically (Key) Key_16bit(HID_CONSUMER_AC_DISTRIBUTE_VERTICALLY, KEY_FLAGS | SYNTHETIC|IS_CONSUMER  | HID_TYPE_SEL)
